Repository scania-digital-design-system/tegel, pull requests merged in 2023-11, with the labels that each got.

#405 docs(readme): amplify links updates
  packages/angular/README.md
  packages/core/README.md
  packages/react/README.md
Labels: 📜 docs

#406 docs(tegel): update readme to start development enviroment
  README.md
Labels: 📜 docs

#409 build(release-script): removed old release script
  packages/core/package.json
  packages/core/tegel-release.sh
Labels: 🏗️ build

#417 build(stencil): upgrade to 4.7.1
  packages/core/package-lock.json
  packages/core/package.json
Labels: 🏗️ build

#408 build: removed dotenv dependency
  packages/core/.storybook/main.cjs
  packages/core/package-lock.json
  packages/core/package.json
Labels: 🏗️ build

#420 chore: update create-release-pr job
  .github/workflows/bump-npm-version.yml
  .github/workflows/chromatic.yml
  .github/workflows/create-release-pr.yml
  .github/workflows/playwright.yml
  .github/workflows/release-angular.yml
  .github/workflows/release-core.yml
  .github/workflows/release-react.yml
  .prettierignore
  package.json
Labels: 🏗️ build

#376 fix(tabs): unset z index
  packages/core/src/components/tabs/folder-tabs/folder-tab/folder-tab.scss
  packages/core/src/components/tabs/folder-tabs/folder-tabs.scss
  packages/core/src/components/tabs/inline-tabs/inline-tab/inline-tab.scss
  packages/core/src/components/tabs/inline-tabs/inline-tabs.scss
  packages/core/src/components/tabs/navigation-tabs/navigation-tab/navigation-tab.scss
  packages/core/src/components/tabs/navigation-tabs/navigation-tabs.scss
Labels: 🐛 bug, QA

#433 test(button): added unit tests
  packages/core/src/components/button/test/basic/button.e2e.ts
  packages/core/src/components/button/test/basic/button.e2e.ts-snapshots/tds-button-renders-basic-button-correctly-1-linux.png
  packages/core/src/components/button/test/basic/index.html
  packages/core/src/components/button/test/danger/button.e2e.ts
  packages/core/src/components/button/test/danger/button.e2e.ts-snapshots/tds-button-renders-danger-button-correctly-1-linux.png
  packages/core/src/components/button/test/danger/index.html
  packages/core/src/components/button/test/disabled/button.e2e.ts
  packages/core/src/components/button/test/disabled/button.e2e.ts-snapshots/tds-button-renders-disabled-button-correctly-1-linux.png
  packages/core/src/components/button/test/disabled/index.html
  packages/core/src/components/button/test/ghost/button.e2e.ts
  packages/core/src/components/button/test/ghost/button.e2e.ts-snapshots/tds-button-renders-ghost-button-correctly-1-linux.png
  packages/core/src/components/button/test/ghost/index.html
  packages/core/src/components/button/test/icon/button.e2e.ts
  packages/core/src/components/button/test/icon/button.e2e.ts-snapshots/tds-button-renders-icon-button-correctly-1-linux.png
  packages/core/src/components/button/test/icon/index.html
  packages/core/src/components/button/test/secondary/button.e2e.ts
  packages/core/src/components/button/test/secondary/button.e2e.ts-snapshots/tds-button-renders-secondary-button-correctly-1-linux.png
  packages/core/src/components/button/test/secondary/index.html
Labels: 🧪 test

#437 test(message): added unit tests
  packages/core/src/components/message/test/error/index.html
  packages/core/src/components/message/test/error/message.e2e.ts
  packages/core/src/components/message/test/error/message.e2e.ts-snapshots/tds-message-is-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/information/index.html
  packages/core/src/components/message/test/information/message.e2e.ts
  packages/core/src/components/message/test/information/message.e2e.ts-snapshots/tds-message-is-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/success/index.html
  packages/core/src/components/message/test/success/message.e2e.ts
  packages/core/src/components/message/test/success/message.e2e.ts-snapshots/tds-message-is-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/warning/index.html
  packages/core/src/components/message/test/warning/message.e2e.ts
  packages/core/src/components/message/test/warning/message.e2e.ts-snapshots/tds-message-is-rendered-correctly-1-linux.png
Labels: 🧪 test
