Repository scania-digital-design-system/tegel, pull requests merged in 2023-08, with the labels that each got.

#236 fix: rename variant option none to default
  core/src/components/banner/banner.stories.tsx
  core/src/components/banner/banner.tsx
  core/src/components/banner/readme.md
  core/src/components/table/table-header-cell/readme.md
Labels: 🛠 Improvement

#241 fix(chip): double events firing
  core/src/components/chip/chip.tsx
Labels: 🐛 bug

#242 feat(datetime): min & max props
  core/src/components/datetime/datetime.stories.tsx
  core/src/components/datetime/datetime.tsx
  core/src/components/datetime/readme.md
  core/src/components/dropdown/readme.md
  core/src/components/table/table-header-cell/readme.md
Labels: 🛠 Improvement

#243 fix(side-menu): pointer-events, css classes instead of attributes, z-index
  core/src/components/popover-menu/readme.md
  core/src/components/side-menu/side-menu-overlay/side-menu-overlay.scss
  core/src/components/side-menu/side-menu.scss
  core/src/components/side-menu/side-menu.tsx
  core/src/mixins/_z-index.scss
  core/src/stories/patterns/navigation/navigation-manyitems.stories.tsx
Labels: 🛠 Improvement

#248 fix(table): hover on rows
  core/src/components/table/table-body-row-expandable/table-body-row-expandable.tsx
  core/src/components/table/table-body-row/table-body-row.scss
  core/src/components/table/table-body-row/table-body-row.tsx
  core/src/components/table/table-vars.scss
  core/src/components/table/table/table.tsx
Labels: 🛠 Improvement, QA

#249 fix(button): fixed usage of label slot
  core/src/components/button/button.scss
  core/src/components/button/button.tsx
  core/src/components/table/table-header-cell/readme.md
Labels: 🐛 bug

#250 fix(button): added variable for active state on slotted icon
  core/src/components/button/button-vars.scss
  core/src/components/button/button.scss
Labels: 🐛 bug, QA

#247 fix(dropdown): select issues
  core/src/components/dropdown/dropdown-option/dropdown-option.tsx
  core/src/components/dropdown/dropdown.tsx
  core/src/components/dropdown/readme.md
Labels: QA

#253 release: tegel 0.0.12
  core/package-lock.json
  core/package.json
  core/src/components/dropdown/readme.md
Labels: 🎉 release

#251 fix(toast): link component colors
  core/src/components/link/link-vars.scss
  core/src/components/toast/toast.scss
  core/src/components/toast/toast.stories.tsx
Labels: 👩‍🎨 design, 🛠 Improvement

#257 docs(code_style): branching update
  .github/CODE_STYLE.md
Labels: 📜 docs

#255 fix(tabs): clickarea should cover entire tab
  core/src/components/tabs/folder-tabs/folder-tab/folder-tab.scss
  core/src/components/tabs/inline-tabs/inline-tab/inline-tab.scss
  core/src/components/tabs/inline-tabs/inline-tabs.stories.tsx
  core/src/components/tabs/navigation-tabs/navigation-tab/navigation-tab.scss
  core/src/components/tabs/navigation-tabs/navigation-tabs.stories.tsx
Labels: 🐛 bug, QA

#258 fix(datetime): corrected secondary mode variant
  core/src/components/datetime/datetime-vars.scss
  core/src/components/datetime/datetime.scss
  core/src/components/datetime/datetime.tsx
Labels: 🐛 bug

#260 feat(banner): removal of persistent prop
  core/src/components/banner/banner.stories.tsx
  core/src/components/banner/banner.tsx
  core/src/components/banner/readme.md
Labels: 🛠 Improvement, QA

#261 fix(icon): set height/width of svg based on size prop
  core/src/components/icon/icon.scss
  core/src/components/icon/icon.tsx
  core/src/components/side-menu/side-menu.stories.tsx
Labels: 🐛 bug, QA

#263 fix(side menu): collapsed scroll
  core/src/components/side-menu/side-menu-item/side-menu-item.scss
Labels: 🐛 bug, QA

#262 build(stencil): v4
  core/package-lock.json
  core/package.json
Labels: 🛠 Improvement

#264 fix(side menu): slot name
  core/src/components/header/header-dropdown/header-dropdown.tsx
  core/src/components/header/header-dropdown/readme.md
  core/src/components/side-menu/side-menu-dropdown-list-item/side-menu-dropdown-list-item.tsx
  core/src/components/side-menu/side-menu-dropdown/readme.md
  core/src/components/side-menu/side-menu-dropdown/side-menu-dropdown.tsx
  core/src/components/side-menu/side-menu.stories.tsx
  core/src/stories/patterns/navigation/navigation-fewitems.stories.tsx
  core/src/stories/patterns/navigation/navigation-manyitems.stories.tsx
  core/src/stories/patterns/navigation/navigation-user-menu.stories.tsx
Labels: 🐛 bug

#267 feat(dropdown, checkbox): fix multiselect clickable area
  core/src/components/checkbox/checkbox.scss
  core/src/components/dropdown/dropdown-option/dropdown-option.scss
  core/src/components/table/table-header-cell/readme.md
Labels: QA
