Repository scania-digital-design-system/tegel, pull requests merged in 2023-07, with the labels that each got.

#178 fix(chip): css selector for gap
  core/src/components/chip/chip.scss
Labels: 🐛 bug

#186 fix(radio button): wrong color disabled state
  core/src/components/radio-button/radio-button-vars.scss
Labels: 🐛 bug

#182 fix(modal): closing programatically without emitting event
  core/src/components/modal/modal.tsx
Labels: 🐛 bug

#187 fix(tabs): set transition on hover
  core/src/components/tabs/inline-tabs/inline-tab/inline-tab.scss
  core/src/components/tabs/navigation-tabs/navigation-tab/navigation-tab.scss
Labels: 🐛 bug

#179 fix(side-menu): slots
  core/src/components/side-menu/readme.md
  core/src/components/side-menu/side-menu-collapse-button/readme.md
  core/src/components/side-menu/side-menu-collapse-button/side-menu-collapse-button.tsx
  core/src/components/side-menu/side-menu-dropdown-list-item/readme.md
  core/src/components/side-menu/side-menu-dropdown-list-item/side-menu-dropdown-list-item.tsx
  core/src/components/side-menu/side-menu-dropdown-list/readme.md
  core/src/components/side-menu/side-menu-dropdown-list/side-menu-dropdown-list.tsx
  core/src/components/side-menu/side-menu-dropdown/readme.md
  core/src/components/side-menu/side-menu-dropdown/side-menu-dropdown.tsx
  core/src/components/side-menu/side-menu-item/readme.md
  core/src/components/side-menu/side-menu-item/side-menu-item.tsx
  core/src/components/side-menu/side-menu-user-image/readme.md
  core/src/components/side-menu/side-menu-user-image/side-menu-user-image.tsx
  core/src/components/side-menu/side-menu-user/readme.md
  core/src/components/side-menu/side-menu-user/side-menu-user.tsx
  core/src/components/side-menu/side-menu.stories.tsx
  core/src/components/side-menu/side-menu.tsx
Labels: 🛠 Improvement

#196 fix(table): removed dummy-data prop
  core/src/components/table/table-body/readme.md
  core/src/components/table/table-body/table-body.tsx
  core/src/components/table/table-component-batch-actions.stories.tsx
  core/src/components/table/table-component-bodydata.stories.tsx
  core/src/components/table/table-component-filtering.stories.tsx
  core/src/components/table/table-component-multiselect.stories.tsx
  core/src/components/table/table-component-pagination.stories.tsx
  core/src/components/table/table-component-sorting.stories.tsx
  core/src/components/table/table-header-cell/readme.md
Labels: 🚨 breaking

#198 fix(dropdown): move open dir calc to render
  core/src/components/dropdown/dropdown.tsx
  core/src/components/table/table-header-cell/readme.md
Labels: 🐛 bug

#199 fix(button): padding for button with icon
  core/src/components/button/button.scss
  core/src/components/button/button.tsx
Labels: 🐛 bug

#143 build: update to node 18
  .npmrc
  README.md
  core/.storybook/main.js
  core/README.md
  core/package-lock.json
  core/package.json
  package-lock.json
  package.json
Labels: 🏗️ build

#201 feat(table-footer): refactored pagination logic and implementation
  core/src/components/table/table-component-event-listeners.stories.tsx
  core/src/components/table/table-component-pagination.stories.tsx
  core/src/components/table/table-footer/readme.md
  core/src/components/table/table-footer/table-footer.tsx
Labels: 🚨 breaking

#203 fix(table:sorting): fixed width on icon to prevent content jump
  core/src/components/table/table-header-cell/table-header-cell.scss
Labels: 🛠 Improvement

#197 docs(storybook): stories sorting and hierarchy
  core/.storybook/preview.js
  core/src/components/accordion/accordion.stories.tsx
  core/src/components/badge/badge.stories.tsx
  core/src/components/banner/banner.stories.tsx
  core/src/components/block/block.stories.tsx
  core/src/components/breadcrumbs/breadcrumbs.stories.tsx
  core/src/components/button/button.stories.tsx
  core/src/components/card/card.stories.tsx
  core/src/components/checkbox/checkbox.stories.tsx
  core/src/components/chip/chip.stories.tsx
  core/src/components/datetime/datetime.stories.tsx
  core/src/components/divider/divider.stories.tsx
  core/src/components/dropdown/dropdown.stories.tsx
  core/src/components/footer/footer.stories.tsx
  core/src/components/header/header.stories.tsx
  core/src/components/link/link.stories.tsx
  core/src/components/message/message.stories.tsx
  core/src/components/modal/modal.stories.tsx
  core/src/components/popover-canvas/popover-canvas.stories.tsx
  core/src/components/popover-menu/popover-menu.stories.tsx
  core/src/components/radio-button/radio-button.stories.tsx
  core/src/components/side-menu/side-menu.stories.tsx
  core/src/components/slider/slider.stories.tsx
  core/src/components/spinner/spinner.stories.tsx
  core/src/components/stepper/stepper.stories.tsx
  core/src/components/table/table-component-basic.stories.tsx
  core/src/components/tabs/folder-tabs/folder-tabs.stories.tsx
  core/src/components/tabs/inline-tabs/inline-tabs.stories.tsx
  core/src/components/tabs/navigation-tabs/navigation-tabs.stories.tsx
  core/src/components/text-field/text-field.stories.tsx
  core/src/components/textarea/textarea.stories.tsx
  core/src/components/toast/toast.stories.tsx
  core/src/components/toggle/toggle.stories.tsx
  core/src/components/tooltip/tooltip.stories.tsx
Labels: 📜 docs, 🛠 Improvement

#200 fix(stepper): adjust Stepper layout to not force space between Steps
  core/src/components/stepper/stepper.scss
Labels: 🐛 bug

#205 feat: adding .npmignore
  core/.npmignore
  core/src/components/card/card.stories.tsx
  core/tsconfig.json
Labels: 🏗️ build, 🛠 Improvement

#208 build: update dependencies
  core/package-lock.json
  core/package.json
  package-lock.json
Labels: dependencies

#209 fix(chip): focus background color
  core/src/components/chip/chip-vars.scss
  core/src/components/chip/chip.scss
Labels: 🛠 Improvement

#211 fix(slider): disabled state update in runtime
  core/src/components/slider/slider.tsx
Labels: 🐛 bug

#213 fix(chip): spacing & slots
  core/package-lock.json
  core/src/components/chip/chip.scss
  core/src/components/chip/chip.stories.tsx
  core/src/components/chip/chip.tsx
  core/src/components/chip/readme.md
  core/src/components/table/table-header-cell/readme.md
  package-lock.json
Labels: 🛠 Improvement

#210 refactor(popover, tooltip): share code instead of duplicating
  core/src/components/core-popover/readme.md
  core/src/components/core-popover/tds-core-popover.tsx
  core/src/components/header/header-dropdown/readme.md
  core/src/components/header/header-launcher/readme.md
  core/src/components/popover-canvas/popover-canvas.scss
  core/src/components/popover-canvas/popover-canvas.tsx
  core/src/components/popover-canvas/readme.md
  core/src/components/popover-menu/popover-menu.scss
  core/src/components/popover-menu/popover-menu.stories.tsx
  core/src/components/popover-menu/popover-menu.tsx
  core/src/components/popover-menu/readme.md
  core/src/components/tooltip/readme.md
  core/src/components/tooltip/tooltip.stories.tsx
  core/src/components/tooltip/tooltip.tsx
Labels: 🪆 refactor

#214 chore: release 0.0.10
  core/package-lock.json
  core/package.json
Labels: 🎉 release

#215 fix(popover): refactor faulty left-start option for popover positioning
  core/src/components/chip/readme.md
  core/src/components/popover-canvas/popover-canvas.stories.tsx
  core/src/components/popover-menu/popover-menu.stories.tsx
  core/src/components/popover-menu/readme.md
  core/src/components/table/table-header-cell/readme.md
  core/src/components/tooltip/readme.md
Labels: 🐛 bug

#222 fix(button): disabled state and pointer events
  core/src/components/button/button.scss
  core/src/components/button/button.tsx
Labels: 🛠 Improvement

#223 fix(card): class and rule for body image
  core/src/components/card/card.scss
  core/src/components/card/card.stories.tsx
  core/src/components/card/card.tsx
Labels: 🛠 Improvement

#224 fix(footer): horizontal scroll issue
  core/src/components/footer/footer.scss
Labels: 🐛 bug

#226 refactor(popover-core): rename and move
  core/src/components/header/header-dropdown/readme.md
  core/src/components/header/header-launcher/readme.md
  core/src/components/popover-canvas/popover-canvas.tsx
  core/src/components/popover-canvas/readme.md
  core/src/components/popover-core/popover-core.tsx
  core/src/components/popover-core/readme.md
  core/src/components/popover-menu/popover-menu.tsx
  core/src/components/popover-menu/readme.md
  core/src/components/tooltip/readme.md
  core/src/components/tooltip/tooltip.tsx
Labels: 🪆 refactor

#227 fix(link): span instead of div for inline alignment
  core/src/components/link/link.stories.tsx
  core/src/components/link/link.tsx
Labels: 🛠 Improvement

#229 refactor(toast): variant instead of type prop
  core/src/components/toast/readme.md
  core/src/components/toast/toast.stories.tsx
  core/src/components/toast/toast.tsx
Labels: 🪆 refactor, 🔍 Needs review

#230 refactor(banner): variant instead of type prop
  core/src/components/banner/banner.stories.tsx
  core/src/components/banner/banner.tsx
  core/src/components/banner/readme.md
Labels: 🔍 Needs review

#232 refactor(header): size instead of type prop
  core/src/components/header/header-dropdown-list-item/header-dropdown-list-item.scss
  core/src/components/header/header-dropdown-list-item/header-dropdown-list-item.tsx
  core/src/components/header/header-dropdown-list-item/readme.md
  core/src/components/header/header-dropdown-list/header-dropdown-list.scss
  core/src/components/header/header-dropdown-list/header-dropdown-list.tsx
  core/src/components/header/header-dropdown-list/readme.md
  core/src/components/header/header-launcher-list-item/header-launcher-list-item.tsx
  core/src/components/header/header-launcher-list/header-launcher-list.tsx
  core/src/stories/patterns/navigation/navigation-fewitems.stories.tsx
  core/src/stories/patterns/navigation/navigation-manyitems.stories.tsx
  core/src/stories/patterns/navigation/navigation-user-menu.stories.tsx
Labels: 🔍 Needs review

#233 fix(dropdown): remove emit on setting default value
  core/src/components/dropdown/dropdown.tsx
Labels: 🐛 bug

#234 Release/release 0.0.11
  core/package-lock.json
  core/package.json
  package-lock.json
  package.json
Labels: 🎉 release
