Repository scania-digital-design-system/tegel, pull requests merged in 2023-10, with the labels that each got.

#340 docs(dropdown): removed TODOs and added link to future issue
  packages/core/src/components/dropdown/dropdown.tsx
Labels: 📜 docs

#344 fix(side menu): collapsed by default
  packages/core/src/components/side-menu/side-menu-collapse-button/side-menu-collapse-button.tsx
  packages/core/src/components/side-menu/side-menu-dropdown-list-item/side-menu-dropdown-list-item.tsx
  packages/core/src/components/side-menu/side-menu-dropdown-list/side-menu-dropdown-list.tsx
  packages/core/src/components/side-menu/side-menu-dropdown/side-menu-dropdown.tsx
  packages/core/src/components/side-menu/side-menu-item/side-menu-item.tsx
  packages/core/src/components/side-menu/side-menu.stories.tsx
Labels: 🐛 bug

#346 fix: add ESLint rule to prevent importing from Stencils internal package
  .eslintrc.json
  packages/core/src/components/dropdown/dropdown-option/dropdown-option.tsx
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/footer/footer-group/footer-group.tsx
  packages/core/src/components/footer/footer.tsx
  packages/core/src/components/stepper/stepper.tsx
  packages/core/src/components/tabs/inline-tabs/inline-tabs.tsx
  packages/core/src/components/toast/toast.tsx
Labels: 🏗️ build

#348 build(stencil): bumped stencil version
  packages/core/package-lock.json
  packages/core/package.json
Labels: 🏗️ build

#341 fix(css reset/components): added important for slotted(*) targeted elements font styles
  packages/core/src/components/card/card.scss
  packages/core/src/components/modal/modal.scss
  packages/core/src/components/tabs/folder-tabs/folder-tab/folder-tab.scss
  packages/core/src/components/tabs/inline-tabs/inline-tab/inline-tab.scss
  packages/core/src/components/tabs/navigation-tabs/navigation-tab/navigation-tab.scss
  packages/core/src/components/toast/toast.scss
Labels: 🐛 bug

#345 fix(modal): leaked CSS
  packages/core/src/components/modal/modal.scss
  packages/core/src/global/global.scss
Labels: 🐛 bug

#349 fix(button): icon color correction
  packages/core/src/components/button/button-vars.scss
  packages/core/src/components/button/button.scss
Labels: QA

#351 build(tsconfig): eliminate conflicts
  packages/react/tsconfig.json
  tsconfig.json
Labels: 🏗️ build

#354 build: config
  packages/core/src/components/dropdown/dropdown-option/dropdown-option.tsx
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/table/table.filtering.spec.tsx
  packages/core/tsconfig.json
  packages/react/tsconfig.json
  tsconfig.json
Labels: 🏗️ build

#320 chromatic: added chromatic workflow
  .github/workflows/chromatic.yml
Labels: chromatic 🎨

#355 fix(chromatic): added --exit-once-uploaded flag
  .github/workflows/chromatic.yml
Labels: 🧪 test

#353 fix(modal): prevent text selection when toggling modal
  packages/core/src/components/modal/modal.scss
  packages/core/src/components/modal/modal.stories.tsx
  packages/core/src/components/modal/modal.tsx
Labels: 🍾 improvement

#361 fix(dropdown): fix multiselect & filter getting value "undefined"
  packages/core/src/components/dropdown/dropdown.tsx
Labels: 🐛 bug

#352 feat(checkbox): indeterminate state
  packages/core/src/components/checkbox/checkbox-vars.scss
  packages/core/src/components/checkbox/checkbox.scss
  packages/core/src/components/checkbox/checkbox.stories.tsx
  packages/core/src/components/checkbox/checkbox.tsx
  packages/core/src/components/checkbox/readme.md
  packages/core/src/components/checkbox/test/checkbox.e2e.ts
  packages/core/src/components/checkbox/test/checkbox.spec.tsx
Labels: 🧪 test, QA, 🆕 feature

#362 docs(tooltip,modal,popover): referenceEl usage in Angular/React
  packages/core/src/components/modal/readme.md
  packages/core/src/components/popover-canvas/readme.md
  packages/core/src/components/popover-menu/readme.md
  packages/core/src/components/tooltip/readme.md
Labels: 📜 docs

#369 feat(slider): update value onblur
  packages/core/src/components/slider/slider.tsx
  packages/core/src/components/slider/test/slider.e2e.ts
Labels: 🧪 test, 🆕 feature

#366 fix(breadcrumb): correct focus state
  packages/core/src/components/breadcrumbs/breadcrumb/breadcrumb.scss
  packages/core/src/components/breadcrumbs/breadcrumbs.tsx
Labels: 🐛 bug, QA

#367 fix(toast): enable for runtime updates of the hidden prop
  packages/core/src/components/toast/toast.stories.tsx
  packages/core/src/components/toast/toast.tsx
Labels: 🍾 improvement

#370 fix(footer): link/title correct font
  packages/core/src/components/footer/footer-item/footer-item.scss
Labels: 🐛 bug, QA

#372 feat(table): add inderminate state & updated selected prop
  packages/core/src/components/table/table-component-multiselect.stories.tsx
  packages/core/src/components/table/table-header/readme.md
  packages/core/src/components/table/table-header/table-header.tsx
Labels: QA, 🆕 feature

#363 build(core/react/angular): added release actions for all packages
  .github/workflows/release-angular.yml
  .github/workflows/release-core.yml
  .github/workflows/release-react.yml
Labels: 🏗️ build

#382 docs(datetime): correct the setting of max prop
  packages/core/src/components/datetime/datetime.stories.tsx
Labels: 📚 storybook

#398 fix: stepper hideLabels in runtime
  packages/core/src/components/stepper/step/step.tsx
Labels: 🐛 bug

#381 docs: "native" components -> css class components
  packages/core/src/stories/Migration/Migration.stories.mdx
  packages/core/src/stories/announcements/announce-tegel.stories.ts
  packages/core/src/stories/tegel.stories.ts
Labels: 📜 docs

#396 fix(button): correct font-size for icon button
  packages/core/src/components/button/button.scss
Labels: 🐛 bug, QA

#400 fix(dropdown): error focus state style alignment
  packages/core/src/components/dropdown/dropdown-button.scss
  packages/core/src/components/dropdown/dropdown-filter.scss
  packages/core/src/components/dropdown/dropdown.tsx
Labels: 🐛 bug

#395 build(node): version 20
  package-lock.json
  package.json
Labels: 🏗️ build
