Repository scania-digital-design-system/tegel, pull requests merged in 2023-05, with the labels that each got.

#14 fix(popover-menu-item): updated import to include popover-menu-item
  core/src/global/global.scss
Labels: 🐛 bug

#15 docs(readme): remove tegel readme
  README.md
  core/readme.md
Labels: 📜 docs

#18 build(release): 0.0.71-beta
  core/README.md
  core/package-lock.json
  core/package.json
Labels: 🎉 release

#19 fix(button): made the button non-clickable when disabled
  core/src/components/button/button.scss
  core/src/components/button/button.stories.tsx
  core/src/components/button/button.tsx
Labels: 🐛 bug

#21 chore(readme): moved readme to be in root folder
  README.md
Labels: 📜 docs

#22 fix(button): updated margin-left on sdds-icon inside btn, removed rules for fullbleed
  core/src/components/button/button.scss
Labels: 🐛 bug

#29 feat(typography): prefix change
  core/src/stories/foundations/typography/typography-body.stories.tsx
  core/src/stories/foundations/typography/typography-detail.stories.tsx
  core/src/stories/foundations/typography/typography-headline.stories.tsx
  core/src/stories/foundations/typography/typography-paragraph.stories.tsx
  typography/scania-fonts-selectors.scss
  typography/scania-fonts-vars.scss
Labels: 🚨 breaking

#31 docs(github-template): removing request help template
  .github/ISSUE_TEMPLATE/REQUEST_HELP.yaml
Labels: 📜 docs

#34 feat(color): prefix change
  color/_color.scss
  color/package.json
  core/src/stories/foundations/color/color-brand.stories.tsx
  core/src/stories/foundations/color/color-scales.stories.tsx
  core/src/stories/foundations/color/color-semantic.stories.tsx
  globals.scss
Labels: 🚨 breaking, 📚 storybook

#33 fix(button): made disabled button non-clickable
  core/src/components/button/button.scss
  core/src/components/button/button.tsx
  core/src/components/button/readme.md
  core/src/utils/utils.ts
Labels: 🐛 bug

#36 feat(logotype): used prefix const
  core/src/global/_logotypes.scss
Labels: 🚨 breaking

#35 feat(grid): prefix change
  core/src/stories/foundations/grid/grid.stories.tsx
  grid/_breakpoints.scss
  grid/_grid.scss
  grid/_mixins.scss
  grid/package.json
  grid/spacing-vars.scss
Labels: 🚨 breaking, 📚 storybook

#38 fix(core): removing storybook
  core/package-lock.json
  core/package.json
  package-lock.json
  package.json
Labels: 🏗️ build, 📚 storybook, 🧐 investigation

#44 feat(utility classes): prefix change
  core/src/global/_utility-classes.scss
  core/src/stories/utility/color/background-color.stories.tsx
  core/src/stories/utility/color/text-color.stories.tsx
  core/src/stories/utility/utility-classes/display.stories.mdx
  core/src/stories/utility/utility-classes/float.stories.mdx
  core/src/stories/utility/utility-classes/height.stories.mdx
  core/src/stories/utility/utility-classes/margin.stories.mdx
  core/src/stories/utility/utility-classes/opacity.stories.mdx
  core/src/stories/utility/utility-classes/overflow.stories.mdx
  core/src/stories/utility/utility-classes/padding.stories.mdx
  core/src/stories/utility/utility-classes/placement.stories.mdx
  core/src/stories/utility/utility-classes/position.stories.mdx
  core/src/stories/utility/utility-classes/text-alignment.stories.mdx
  core/src/stories/utility/utility-classes/visibility.stories.mdx
  core/src/stories/utility/utility-classes/width.stories.mdx
  core/src/stories/utility/utility-classes/z-index.stories.mdx
Labels: 🚨 breaking

#43 docs(code-style): branching section
  .github/CODE_STYLE.md
Labels: 📜 docs

#47 docs(prefix change): changed prefix for the mode change in storybook
  .storybook/ScaniaThemeDark.js
  .storybook/ScaniaThemeLight.js
  .storybook/preview.js
Labels: 🚨 breaking

#39 feat(accordion): prefix change
  core/src/components/accordion/accordion-item/accordion-item.scss
  core/src/components/accordion/accordion-item/accordion-item.tsx
  core/src/components/accordion/accordion-item/readme.md
  core/src/components/accordion/accordion-vars.scss
  core/src/components/accordion/accordion.scss
  core/src/components/accordion/accordion.spec.ts
  core/src/components/accordion/accordion.stories.tsx
  core/src/components/accordion/accordion.tsx
  core/src/components/accordion/readme.md
  core/src/components/icon/readme.md
  core/src/stories/Migration/Migration.stories.mdx
Labels: 🚨 breaking

#51 chore(tooltip): use singular Capital Case where possible
  core/src/components/tooltip/readme.md
  core/src/components/tooltip/tooltip.stories.tsx
  core/src/components/tooltip/tooltip.tsx
Labels: 📜 docs

#53 chore(toast): use singular Capital Case where possible
  core/src/components/toast/readme.md
  core/src/components/toast/sdds-toast.tsx
Labels: 📜 docs

#54 chore(spinner): use singular Capital Case where possible
  core/src/components/spinner/readme.md
  core/src/components/spinner/spinner.stories.tsx
  core/src/components/spinner/spinner.tsx
Labels: 📜 docs

#57 chore(side menu): use singular Capital Case where possible
  core/src/components/header/webcomponent/header-hamburger/readme.md
  core/src/components/side-menu/readme.md
  core/src/components/side-menu/webcomponent/readme.md
  core/src/components/side-menu/webcomponent/side-menu-close-button/readme.md
  core/src/components/side-menu/webcomponent/side-menu-collapse-button/readme.md
  core/src/components/side-menu/webcomponent/side-menu-collapse-button/side-menu-collapse-button.tsx
  core/src/components/side-menu/webcomponent/side-menu-dropdown/readme.md
  core/src/components/side-menu/webcomponent/side-menu-overlay/readme.md
  core/src/components/side-menu/webcomponent/side-menu-user/readme.md
  core/src/components/side-menu/webcomponent/side-menu-webcomponent.stories.tsx
  core/src/components/side-menu/webcomponent/side-menu.tsx
Labels: 📜 docs

#52 chore(toggle): use singular Capital Case where possible
  core/src/components/toggle/readme.md
  core/src/components/toggle/sdds-toggle.stories.tsx
  core/src/components/toggle/sdds-toggle.tsx
Labels: 📜 docs

#59 chore(radio button): use singular Capital Case where possible & file renaming
  core/src/components/radio-button/radio-button.scss
  core/src/components/radio-button/radio-button.stories.tsx
  core/src/components/radio-button/radio-button.tsx
  core/src/components/radio-button/readme.md
Labels: 📜 docs

#61 chore(popover): use singular Capital Case where possible
  core/src/components/accordion/accordion-item/readme.md
  core/src/components/data-table/table-header-cell/readme.md
  core/src/components/popover-canvas/documentation.txt
  core/src/components/popover-canvas/popover-canvas.stories.tsx
  core/src/components/popover-canvas/popover-canvas.tsx
  core/src/components/popover-canvas/readme.md
  core/src/components/popover-menu/documentation.txt
  core/src/components/popover-menu/popover-menu.stories.tsx
  core/src/components/popover-menu/popover-menu.tsx
  core/src/components/popover-menu/readme.md
  core/src/components/toggle/readme.md
Labels: 📜 docs

#41 feat(icons): add new document icons
  .eslintignore
  core/src/components/icon/iconsArray.js
  icons/gulpfile.js
  icons/src/svg/document_doc.svg
  icons/src/svg/document_pdf.svg
  icons/src/svg/document_ppt.svg
  icons/src/svg/document_xls.svg
Labels: 👩‍🎨 design

#77 feat(breadcrumbs): prefix change
  core/src/components/breadcrumb/breadcrumb-vars.scss
  core/src/components/breadcrumbs/breadcrumb/breadcrumb.scss
  core/src/components/breadcrumbs/breadcrumb/breadcrumb.tsx
  core/src/components/breadcrumbs/breadcrumb/readme.md
  core/src/components/breadcrumbs/breadcrumbs-vars.scss
  core/src/components/breadcrumbs/breadcrumbs.scss
  core/src/components/breadcrumbs/breadcrumbs.stories.tsx
  core/src/components/breadcrumbs/breadcrumbs.tsx
  core/src/components/breadcrumbs/readme.md
  core/src/global/global.scss
Labels: 🚨 breaking

#80 feat(checkbox): prefix change
  core/src/components/checkbox/checkbox-vars.scss
  core/src/components/checkbox/checkbox.scss
  core/src/components/checkbox/checkbox.stories.tsx
  core/src/components/checkbox/checkbox.tsx
  core/src/components/checkbox/readme.md
  core/src/components/dropdown-v2/dropdown-option-v2/dropdown-option-v2.tsx
Labels: 🚨 breaking

#79 docs(readme): added readme to the core package
  core/README.md
Labels: 📜 docs

#83 feat(message): prefix change
  core/src/components/icon/readme.md
  core/src/components/message/message-vars.scss
  core/src/components/message/message.scss
  core/src/components/message/message.stories.tsx
  core/src/components/message/message.tsx
  core/src/components/message/readme.md
  core/src/components/message/sdds-message.scss
Labels: 🚨 breaking

#85 feat(slider): prefix change
  core/src/components/icon/readme.md
  core/src/components/slider/documentation.txt
  core/src/components/slider/readme.md
  core/src/components/slider/slider-vars.scss
  core/src/components/slider/slider.scss
  core/src/components/slider/slider.stories.tsx
  core/src/components/slider/slider.tsx
Labels: 🚨 breaking

#81 feat(datepicker): prefix change
  core/src/components/data-table/table-header-cell/readme.md
  core/src/components/datetime/datetime-vars.scss
  core/src/components/datetime/datetime.scss
  core/src/components/datetime/datetime.stories.tsx
  core/src/components/datetime/datetime.tsx
  core/src/components/datetime/readme.md
  core/src/components/icon/readme.md
  core/src/stories/Migration/Migration.stories.mdx
Labels: 🚨 breaking

#93 fix(toggle/toast/textarea/message/dropdown-v2): added root selector to get light mode by default
  core/src/components/dropdown-v2/dropdown-vars.scss
  core/src/components/message/message-vars.scss
  core/src/components/textarea/textarea-vars.scss
  core/src/components/toast/toast-vars.scss
  core/src/components/toggle/toggle-vars.scss
Labels: 🐛 bug

#92 docs(web links): updated web links pointing to digitaldesign -> tegel
  core/src/components/icon/icon.tsx
  core/src/components/icon/readme.md
  core/src/components/popover-canvas/documentation.txt
  core/src/components/popover-canvas/popover-canvas.stories.tsx
  core/src/components/popover-menu/documentation.txt
  core/src/components/popover-menu/popover-menu.stories.tsx
Labels: 📜 docs

#99 chore: move storybook to core folder
  .eslintignore
  .storybook/main.js
  core/.storybook/ScaniaThemeDark.js
  core/.storybook/ScaniaThemeLight.js
  core/.storybook/assets/svg/ScaniaLogotype.svg
  core/.storybook/assets/svg/ScaniaLogotypeDarkMode.svg
  core/.storybook/main.js
  core/.storybook/manager-head.html
  core/.storybook/manager.js
  core/.storybook/preview-head.html
  core/.storybook/preview.css
  core/.storybook/preview.js
  core/.storybook/scaniaThemeCommon.js
  core/package-lock.json
  core/package.json
  core/public/android-chrome-192x192.png
  core/public/android-chrome-512x512.png
  core/public/apple-touch-icon.png
  core/public/favicon-16x16.png
  core/public/favicon-32x32.png
  core/public/favicon.ico
  core/public/site.webmanifest
  package-lock.json
  package.json
  tsconfig.json
Labels: 🏗️ build

#98 docs(repo): updated link to correct repo and teams channel
  core/src/stories/Tegel.stories.mdx
Labels: 📜 docs

#100 build(stecil version): stencil v 3.3.0, node and enableImportInjection
  .npmrc
  core/package-lock.json
  core/package.json
  core/stencil.config.ts
Labels: 🏗️ build

#101 build: adding build command to root
  package.json
Labels: 🏗️ build

#105 docs: readme update
  core/src/components/card/readme.md
  core/src/components/divider/readme.md
  core/src/components/dropdown-v2/dropdown-option-v2/readme.md
  core/src/components/dropdown/dropdown-filter/readme.md
  core/src/components/dropdown/dropdown-option/readme.md
  core/src/components/icon/readme.md
Labels: 📜 docs

#110 fix(:root) css selector
  core/src/components/breadcrumb/readme.md
  core/src/components/breadcrumb/sdds-breadcrumb-item/readme.md
  core/src/components/icon/readme.md
  core/src/components/message/message-vars.scss
  core/src/components/spinner/spinner-vars.scss
  core/src/components/table/table-header-cell/readme.md
  core/src/components/toggle/toggle-vars.scss
Labels: 🐛 bug

#107 feat(link): prefix change
  core/src/components/link/link-vars.scss
  core/src/components/link/link.scss
  core/src/components/link/link.stories.tsx
  core/src/components/link/link.tsx
  core/src/components/link/readme.md
Labels: 🚨 breaking

#109 feat(toast): prefix change
  core/src/components/icon/readme.md
  core/src/components/toast/readme.md
  core/src/components/toast/toast-vars.scss
  core/src/components/toast/toast.scss
  core/src/components/toast/toast.stories.tsx
  core/src/components/toast/toast.tsx
Labels: 🚨 breaking

#108 feat(text field): prefix and component name change
  core/src/components/icon/readme.md
  core/src/components/text-field/readme.md
  core/src/components/text-field/text-field-vars.scss
  core/src/components/text-field/text-field.scss
  core/src/components/text-field/text-field.stories.tsx
  core/src/components/text-field/text-field.tsx
  core/src/components/textfield/textfield-vars.scss
  core/src/components/textfield/textfield.scss
  core/src/global/global.scss
  core/src/stories/Migration/Migration.stories.mdx
Labels: 🚨 breaking

#111 feat(radiobutton): prefix change
  core/src/components/radio-button/radio-button-vars.scss
  core/src/components/radio-button/radio-button.scss
  core/src/components/radio-button/radio-button.stories.tsx
  core/src/components/radio-button/radio-button.tsx
  core/src/components/radio-button/readme.md
Labels: 🚨 breaking

#112 feat(tooltip): prefix change
  core/src/components/tooltip/readme.md
  core/src/components/tooltip/tooltip-vars.scss
  core/src/components/tooltip/tooltip.scss
  core/src/components/tooltip/tooltip.stories.tsx
  core/src/components/tooltip/tooltip.tsx
Labels: 🚨 breaking

#113 feat(stepper): prefix change + singular capital case
  core/src/components/icon/readme.md
  core/src/components/stepper/readme.md
  core/src/components/stepper/step/readme.md
  core/src/components/stepper/step/step.scss
  core/src/components/stepper/step/step.tsx
  core/src/components/stepper/stepper-item/readme.md
  core/src/components/stepper/stepper-vars.scss
  core/src/components/stepper/stepper.scss
  core/src/components/stepper/stepper.stories.tsx
  core/src/components/stepper/stepper.tsx
  core/src/components/table/table-header-cell/readme.md
Labels: 🚨 breaking

#114 feat(dropdown): prefix change
  core/src/components/checkbox/readme.md
  core/src/components/dropdown-v2/dropdown-button.scss
  core/src/components/dropdown-v2/dropdown-filter.scss
  core/src/components/dropdown-v2/dropdown-option-v2/dropdown-option-v2.scss
  core/src/components/dropdown-v2/dropdown-option-v2/dropdown-option-v2.tsx
  core/src/components/dropdown-v2/dropdown-option-v2/dropdown-option-vars.scss
  core/src/components/dropdown-v2/dropdown-option-v2/readme.md
  core/src/components/dropdown-v2/dropdown-v2.scss
  core/src/components/dropdown-v2/dropdown-v2.stories.tsx
  core/src/components/dropdown-v2/dropdown-v2.tsx
  core/src/components/dropdown-v2/dropdown-vars.scss
  core/src/components/dropdown-v2/readme.md
  core/src/components/dropdown/_dropdown-core.scss
  core/src/components/dropdown/dropdown-filter/dropdown-filter.tsx
  core/src/components/dropdown/dropdown-filter/readme.md
  core/src/components/dropdown/dropdown-option/dropdown-option.tsx
  core/src/components/dropdown/dropdown-option/readme.md
  core/src/components/dropdown/dropdown-select.scss
  core/src/components/dropdown/dropdown-vars.scss
  core/src/components/dropdown/dropdown.scss
  core/src/components/dropdown/dropdown.stories.tsx
  core/src/components/dropdown/dropdown.tsx
  core/src/components/dropdown/readme.md
  core/src/components/icon/readme.md
  core/src/components/table/table-header-cell/readme.md
Labels: 🚨 breaking

#123 chore(readme): restructure readmes
  .github/CODE_STYLE.md
  README.md
  core/README.md
Labels: 📜 docs

#128 docs(icon size): updated icon size control to be select instead of range
  core/src/components/icon/icon-font.stories.tsx
  core/src/components/icon/icon-web-component.stories.tsx
Labels: 📚 storybook

#126 feat(header): brand link
  core/src/components/header/header-brand-symbol/header-brand-symbol.scss
  core/src/components/header/header-brand-symbol/header-brand-symbol.tsx
  core/src/components/header/header-brand-symbol/readme.md
  core/src/components/header/header.stories.tsx
  core/src/components/side-menu/side-menu.stories.tsx
  core/src/stories/patterns/navigation/navigation-basic.stories.tsx
  core/src/stories/patterns/navigation/navigation-fewitems.stories.tsx
  core/src/stories/patterns/navigation/navigation-manyitems.stories.tsx
  core/src/stories/patterns/navigation/navigation-user-menu.stories.tsx
Labels: 🚨 breaking
