Repository scania-digital-design-system/tegel, pull requests merged in 2023-09, with the labels that each got.

#271 fix(modal/toast/banner/card): align slot names
  core/src/components/banner/banner.scss
  core/src/components/banner/banner.stories.tsx
  core/src/components/banner/banner.tsx
  core/src/components/banner/readme.md
  core/src/components/card/card.scss
  core/src/components/card/card.stories.tsx
  core/src/components/card/card.tsx
  core/src/components/card/readme.md
  core/src/components/modal/modal.stories.tsx
  core/src/components/modal/modal.tsx
  core/src/components/modal/readme.md
  core/src/components/toast/readme.md
  core/src/components/toast/toast.scss
  core/src/components/toast/toast.stories.tsx
  core/src/components/toast/toast.tsx
Labels: 🚨 breaking

#275 fix(chip): updated tdsChange to include the updated checked value
  core/src/components/chip/chip.tsx
  core/src/components/chip/readme.md
Labels: 🐛 bug

#274 refactor(slider): rename scrubber to thumb
  core/src/components/slider/readme.md
  core/src/components/slider/slider.scss
  core/src/components/slider/slider.stories.tsx
  core/src/components/slider/slider.tsx
  core/src/stories/Migration/Migration.stories.mdx
Labels: 🚨 breaking, 🪆 refactor, QA

#202 feat(table): remove internal logic
  core/src/components/table/table-body-cell/readme.md
  core/src/components/table/table-body-row-expandable/table-body-row-expandable.tsx
  core/src/components/table/table-body-row/readme.md
  core/src/components/table/table-body-row/table-body-row.tsx
  core/src/components/table/table-body/readme.md
  core/src/components/table/table-body/table-body.tsx
  core/src/components/table/table-component-basic.stories.tsx
  core/src/components/table/table-component-batch-actions.stories.tsx
  core/src/components/table/table-component-bodydata.stories.tsx
  core/src/components/table/table-component-custom-width.stories.tsx
  core/src/components/table/table-component-event-listeners.stories.tsx
  core/src/components/table/table-component-expandable-rows.stories.tsx
  core/src/components/table/table-component-filtering.stories.tsx
  core/src/components/table/table-component-multiselect.stories.tsx
  core/src/components/table/table-component-pagination.stories.tsx
  core/src/components/table/table-component-sorting.stories.tsx
  core/src/components/table/table-footer/readme.md
  core/src/components/table/table-footer/table-footer.scss
  core/src/components/table/table-footer/table-footer.tsx
  core/src/components/table/table-header-cell/readme.md
  core/src/components/table/table-header-cell/table-header-cell.tsx
  core/src/components/table/table-header/readme.md
  core/src/components/table/table-header/table-header.tsx
  core/src/components/table/table-toolbar/readme.md
  core/src/components/table/table-toolbar/table-toolbar.scss
  core/src/components/table/table-toolbar/table-toolbar.tsx
  core/src/components/table/table.filtering.spec.tsx
  core/src/components/table/table.spec.tsx
  core/src/components/table/table/readme.md
  core/src/components/table/table/table.tsx
Labels: 🚨 breaking, 🧐 investigation, 🍾 improvement, QA

#278 build(tagNameTransform): enable tagNameTransform
  core/stencil.config.ts
Labels: 🏗️ build

#282 fix(step): corrected css selector
  core/src/components/stepper/step/step.scss
Labels: 🐛 bug

#285 fix(z-index): side-menu over banner
  core/src/mixins/_z-index.scss
Labels: 🍾 improvement

#286 release: tegel 1.0.0-beta
  core/package-lock.json
  core/package.json
Labels: 🎉 release

#289 feat(table-footer): correct color of pagination button icons for both modes
  core/src/components/table/table-footer/table-footer.scss
  core/src/components/table/table-vars.scss
Labels: 🍾 improvement, QA

#291 docs(installation): corrected spelling in HTML installation guide
  core/src/stories/Installation/installation.stories.ts
Labels: 📜 docs

#293 fix(banner): removed docs and implementation of unused event
  core/src/components/banner/banner.stories.tsx
  core/src/components/banner/banner.tsx
  core/src/components/banner/readme.md
Labels: 🐛 bug, 📜 docs

#294 build(stencil.config): prepare stencil build for wrappers
  .eslintignore
  .gitignore
  core/package.json
  core/stencil.config.ts
Labels: 🏗️ build

#296 docs: switched all instances of pre-beta to beta
  README.md
  core/README.md
  core/src/stories/tegel.stories.ts
Labels: 📜 docs

#299 release: 1.0.1
  core/package-lock.json
  core/package.json
Labels: 🎉 release

#303 release: 1.0.2
  core/package-lock.json
  core/package.json
Labels: 🎉 release

#306 fix(dropdown): fixed missplacement issue of the dropdowns focus state
  packages/core/src/components/dropdown/dropdown-button.scss
  packages/core/src/components/dropdown/dropdown.stories.tsx
Labels: 🐛 bug, QA

#308 docs(tegel-angular): updated README
  packages/angular/README.md
Labels: 📜 docs

#309 docs(popover/tooltip): used selector over referenceEl
  packages/core/src/components/popover-menu/popover-menu.stories.tsx
  packages/core/src/components/tooltip/tooltip.stories.tsx
Labels: 📚 storybook

#307 fix(dropdown): stopPropogation on checkbox change event in dropdown-option
  packages/core/src/components/dropdown/dropdown-option/dropdown-option.tsx
Labels: 🐛 bug

#312 fix(dropdown): override line-height to avoid overflow:hidden
  packages/core/src/components/dropdown/dropdown-button.scss
  packages/core/src/components/dropdown/dropdown.stories.tsx
Labels: 🐛 bug

#310 docs(banner): no undefined icon in error and info variant
  packages/core/src/components/banner/banner.stories.tsx
Labels: 🐛 bug, 📜 docs

#314 docs(button): remove unused class from button icon
  packages/core/src/components/button/button.stories.tsx
Labels: 📚 storybook

#313 fix(slider): enable for runtime updates of value/readOnly
  packages/core/src/components/slider/slider.stories.tsx
  packages/core/src/components/slider/slider.tsx
Labels: 🍾 improvement

#321 fix(card): clickable card not full width
  packages/core/src/components/card/card.scss
Labels: 🐛 bug, QA

#324 docs(table): removed obsolete control
  packages/core/src/components/table/table-component-filtering.stories.tsx
Labels: 📚 storybook

#322 fix(tabs): multiple events firing
  packages/core/src/components/tabs/inline-tabs/inline-tabs.tsx
  packages/core/src/components/tabs/navigation-tabs/navigation-tabs.tsx
Labels: 🐛 bug

#323 docs(table): removed obsolete control from story
  packages/core/src/components/table/table-component-multiselect.stories.tsx
Labels: 📚 storybook

#325 fix(block): updating block modeVariant in runtime
  packages/core/src/components/block/block.tsx
Labels: 🐛 bug

#327 fix: typo in Storybook
  packages/core/src/stories/foundations/color/color-semantic.stories.tsx
Labels: QA

#326 fix(dropdown): use getChildren over fetching children in connectedCallback
  packages/core/src/components/dropdown/dropdown.tsx
Labels: 🐛 bug, QA

#329 fix: indentation on installation page in storybook
  packages/core/src/stories/Installation/installation.stories.ts
Labels: QA

#330 feat(icon): enable for override of default title
  packages/core/src/components/icon/icon.tsx
  packages/core/src/components/icon/readme.md
Labels: 🍾 improvement

#316 fix(dropdown): setValue method
  packages/core/src/components/dropdown/dropdown-option/dropdown-option.tsx
  packages/core/src/components/dropdown/dropdown.stories.tsx
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/dropdown/readme.md
Labels: 🐛 bug, QA

#332 fix: remove extra margin under inputs without helper text
  packages/core/src/components/datetime/datetime.tsx
  packages/core/src/components/text-field/text-field.tsx
Labels: 🐛 bug, QA

#328 build(angular): switched angular version to 14
  packages/angular/package-lock.json
  packages/angular/package.json
  packages/angular/projects/components/package-lock.json
  packages/angular/projects/components/package.json
Labels: 🏗️ build

#331 refactor(dropdown): cleanup and enhancement setValue & removeValue
  packages/core/src/components/dropdown/dropdown-option/dropdown-option.tsx
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/dropdown/readme.md
  packages/core/src/components/table/table-header-cell/readme.md
Labels: QA

#333 release(1.0.3): updated package.json
  packages/core/package-lock.json
  packages/core/package.json
Labels: 🎉 release

#339 release(@scania/tegel-angular): 0.0.2
  packages/angular/package-lock.json
  packages/angular/package.json
  packages/angular/projects/components/package.json
Labels: 🎉 release
