Repository scania-digital-design-system/tegel, pull requests merged in 2023-06, with the labels that each got.

#124 docs(prefix change): announce prefix change
  core/.storybook/preview.css
  core/.storybook/preview.js
  core/src/stories/Tegel.stories.mdx
  core/src/stories/announcements/announce-tegel.stories.ts
  core/src/stories/announcements/prefix-change.stories.ts
  core/src/stories/tegel.stories.ts
  core/tsconfig.json
Labels: 📚 storybook, 📜 docs

#131 docs(prefix info): add prefix info in migration docs
  core/src/stories/Migration/Migration.stories.mdx
Labels: 📜 docs

#139 docs: tegel regression
  core/src/components/accordion/accordion-item/accordion-item.tsx
  core/src/components/accordion/accordion-item/readme.md
  core/src/components/accordion/accordion.tsx
  core/src/components/accordion/readme.md
  core/src/components/badge/badge.tsx
  core/src/components/badge/readme.md
  core/src/components/banner/banner.tsx
  core/src/components/banner/readme.md
  core/src/components/breadcrumbs/breadcrumb/breadcrumb.tsx
  core/src/components/breadcrumbs/breadcrumb/readme.md
  core/src/components/checkbox/checkbox.tsx
  core/src/components/checkbox/readme.md
  core/src/components/chip/chip.tsx
  core/src/components/chip/readme.md
  core/src/components/datetime/datetime.tsx
  core/src/components/footer/footer-group/footer-group.tsx
  core/src/components/footer/footer.tsx
  core/src/components/icon/icon.stories.tsx
  core/src/components/modal/modal.tsx
  core/src/components/modal/readme.md
  core/src/components/popover-canvas/documentation.txt
  core/src/components/popover-menu/documentation.txt
  core/src/components/radio-button/radio-button.tsx
  core/src/components/radio-button/readme.md
  core/src/components/side-menu/side-menu-collapse-button/readme.md
  core/src/components/side-menu/side-menu-collapse-button/side-menu-collapse-button.tsx
  core/src/components/slider/documentation.txt
  core/src/components/slider/readme.md
  core/src/components/slider/slider.tsx
  core/src/components/table/table-body-row-expandable/table-body-row-expandable.tsx
  core/src/components/table/table/table.tsx
  core/src/components/tabs/folder-tabs/folder-tab/folder-tab.tsx
  core/src/components/tabs/folder-tabs/folder-tab/readme.md
  core/src/components/tabs/folder-tabs/folder-tabs.stories.tsx
  core/src/components/tabs/folder-tabs/folder-tabs.tsx
  core/src/components/tabs/folder-tabs/readme.md
  core/src/components/tabs/inline-tabs/inline-tab/inline-tab.tsx
  core/src/components/tabs/inline-tabs/inline-tab/readme.md
  core/src/components/tabs/inline-tabs/inline-tabs.stories.tsx
  core/src/components/tabs/inline-tabs/inline-tabs.tsx
  core/src/components/tabs/inline-tabs/readme.md
  core/src/components/tabs/navigation-tabs/navigation-tab/navigation-tab.tsx
  core/src/components/tabs/navigation-tabs/navigation-tab/readme.md
  core/src/components/tabs/navigation-tabs/navigation-tabs.tsx
  core/src/components/tabs/navigation-tabs/readme.md
  core/src/components/text-field/text-field.tsx
  core/src/components/textarea/textarea.tsx
  core/src/components/toast/toast.stories.tsx
  core/src/components/toggle/readme.md
  core/src/components/toggle/toggle.stories.tsx
  core/src/components/toggle/toggle.tsx
  core/src/components/tooltip/readme.md
  core/src/components/tooltip/tooltip.tsx
Labels: 📜 docs

#142 Release/59
  core/package-lock.json
  core/package.json
  core/src/components/table/table-header-cell/readme.md
  package-lock.json
  package.json
Labels: 🎉 release

#145 docs(icons): updated icons story name
  core/src/components/icon/icon.stories.tsx
Labels: 📚 storybook

#147 fix(banner/badge/toast): reflect hidden prop
  core/src/components/badge/badge.tsx
  core/src/components/banner/banner.tsx
  core/src/components/toast/toast.tsx
Labels: 🐛 bug

#148 fix(button): locked in disabled state
  core/src/components/button/button.scss
  core/src/components/button/button.tsx
  core/src/utils/utils.ts
Labels: 🐛 bug

#153 fix(textarea): corrected root selector
  core/src/components/textarea/textarea-vars.scss
Labels: 🐛 bug

#163 docs(events): document removal of event listener in react example
  core/src/stories/Events/Events.stories.mdx
Labels: 📜 docs

#157 fix(slider): disabled state and code hygiene
  core/src/components/slider/slider.tsx
Labels: 🛠 Improvement

#155 fix(banner): align slots
  core/src/components/banner/banner.scss
  core/src/components/banner/banner.stories.tsx
  core/src/components/banner/banner.tsx
  core/src/components/banner/readme.md
  core/src/utils/utils.ts
Labels: 🚨 breaking

#168 docs(slots): documentation for slot naming convention
  .github/CODE_STYLE.md
  core/src/stories/Migration/Migration.stories.mdx
Labels: 📜 docs

#156 feat(toast): align slots
  core/src/components/toast/readme.md
  core/src/components/toast/toast.scss
  core/src/components/toast/toast.stories.tsx
  core/src/components/toast/toast.tsx
  core/src/utils/utils.ts
Labels: 🚨 breaking

#158 feat(card): align slots
  core/src/components/card/card.scss
  core/src/components/card/card.stories.tsx
  core/src/components/card/card.tsx
  core/src/components/card/readme.md
  core/src/utils/utils.ts
Labels: 🚨 breaking

#170 fix(globals): corrected rules for global background and color
  core/src/global/global.scss
Labels: 🐛 bug

#176 fix(tabs): no event emitted on disabled tabs
  core/src/components/tabs/folder-tabs/folder-tabs.tsx
  core/src/components/tabs/inline-tabs/inline-tabs.tsx
  core/src/components/tabs/navigation-tabs/navigation-tabs.tsx
Labels: 🐛 bug

#174 fix(breadcrumbs): last element and disabled corrections
  core/src/components/breadcrumbs/breadcrumb/breadcrumb.scss
  core/src/components/breadcrumbs/breadcrumb/breadcrumb.tsx
  core/src/components/breadcrumbs/breadcrumb/readme.md
  core/src/components/breadcrumbs/breadcrumbs-vars.scss
  core/src/components/breadcrumbs/breadcrumbs.tsx
Labels: 🐛 bug

#175 fix(modal): slot alignment
  core/src/components/modal/modal.scss
  core/src/components/modal/modal.stories.tsx
  core/src/components/modal/modal.tsx
  core/src/components/modal/readme.md
Labels: 🛠 Improvement

#177 fix(dropdown): corrected font
  core/src/components/dropdown/dropdown.scss
Labels: 🐛 bug
