Repository scania-digital-design-system/tegel, pull requests merged in 2024-08, with the labels that each got.

#704 test(stepper): added unit test
  packages/core/src/components/stepper/test/large-horizontal-text-below/index.html
  packages/core/src/components/stepper/test/large-horizontal-text-below/stepper.e2e.ts
  packages/core/src/components/stepper/test/large-horizontal-text-below/stepper.e2e.ts-snapshots/Stepper---Large-horizontal-with-text-below-1-linux.png
  packages/core/src/components/stepper/test/large-vertical-with-text/index.html
  packages/core/src/components/stepper/test/large-vertical-with-text/stepper.e2e.ts
  packages/core/src/components/stepper/test/large-vertical-with-text/stepper.e2e.ts-snapshots/Stepper---Large-vertical-with-text-1-linux.png
  packages/core/src/components/stepper/test/small-vertical-text-aside/index.html
  packages/core/src/components/stepper/test/small-vertical-text-aside/stepper.e2e.ts
  packages/core/src/components/stepper/test/small-vertical-text-aside/stepper.e2e.ts-snapshots/Stepper---Small-vertical-text-aside-1-linux.png
  packages/core/src/components/stepper/test/small-vertical-with-no-text/index.html
  packages/core/src/components/stepper/test/small-vertical-with-no-text/stepper.e2e.ts
  packages/core/src/components/stepper/test/small-vertical-with-no-text/stepper.e2e.ts-snapshots/Stepper---Small-vertical-with-no-text-1-linux.png
Labels: 🧪 test

#598 feat(tegel-angular): reactive forms integration
  packages/angular-17/projects/components/src/lib/components.module.ts
  packages/angular-17/projects/components/src/lib/directives/tds-dropdown-value-accessor.ts
  packages/angular-17/projects/components/src/lib/directives/tds-radio-value-accessor.ts
  packages/angular-17/projects/components/src/public-api.ts
  packages/angular-17/tsconfig.json
  packages/angular/projects/components/src/lib/components.module.ts
  packages/angular/projects/components/src/lib/directives/tds-dropdown-value-accessor.ts
  packages/angular/projects/components/src/lib/directives/tds-radio-value-accessor.ts
  packages/angular/projects/components/src/public-api.ts
  packages/angular/tsconfig.json
  packages/core/src/components/text-field/text-field.tsx
  packages/core/src/components/textarea/textarea.tsx
  packages/core/stencil.config.ts
Labels: 🆕 feature

#705 fix(table): removing unused files and slots
  packages/core/src/components/table/table-body/dummy-data.json
  packages/core/src/components/table/table-body/readme.md
  packages/core/src/components/table/table-body/table-body.tsx
Labels: 🍾 improvement

#706 fix(banner): padding left in no icon variation
  packages/core/src/components/banner/banner.scss
Labels: 🍾 improvement

#707 fix(dropdown): async data source handling
  packages/core/src/components/dropdown/dropdown.tsx
Labels: 🍾 improvement

#710 fix(tabs): enabled runtime updates
  packages/angular-17/package-lock.json
  packages/angular-17/projects/components/package-lock.json
  packages/core/src/components/tabs/folder-tabs/folder-tabs.tsx
  packages/core/src/components/tabs/folder-tabs/readme.md
  packages/core/src/components/tabs/inline-tabs/inline-tabs.tsx
  packages/core/src/components/tabs/inline-tabs/readme.md
  packages/core/src/components/tabs/navigation-tabs/navigation-tabs.tsx
  packages/core/src/components/tabs/navigation-tabs/readme.md
  packages/core/src/components/tabs/test/folder-tabs/folder-tabs.e2e.ts-snapshots/tds-folder-tabs-Click-on-Second-tab-selects-it-and-updates-selected-index-1-linux.png
  packages/core/src/components/tabs/test/folder-tabs/folder-tabs.e2e.ts-snapshots/tds-folder-tabs-Click-on-Third-tab-selects-it-and-updates-selected-index-1-linux.png
  packages/core/src/components/tabs/test/folder-tabs/folder-tabs.e2e.ts-snapshots/tds-folder-tabs-Click-on-tabs-selects-them-and-updates-selected-index-1-linux.png
  packages/core/src/components/tabs/test/folder-tabs/folder-tabs.e2e.ts-snapshots/tds-folder-tabs-renders-folder-tabs-correctly-1-linux.png
Labels: 🍾 improvement

#712 fix(slider): runtime issue
  packages/core/src/components/slider/slider.tsx
Labels: 🍾 improvement

#713 refactor(header-title): code clean-up and improvement
  packages/core/src/components/header/header-title/header-title.scss
  packages/core/src/components/header/header-title/header-title.tsx
  packages/core/src/components/header/header.scss
Labels: 🍾 improvement, 🪆 refactor

#715 ci(release-all): setup github user
  .github/workflows/release-all.yml
Labels: 🎉 release

#717 fix(tegel-styles): ag-grid-overwrites clean up
  packages/styles/scss/ag-grid/ag-grid-styles.scss
Labels: 🍾 improvement

#731 docs(tegel-styles): readme update
  LICENSE
  packages/styles/README.md
Labels: 📜 docs

#734 test(spinner): added unit test
  packages/core/src/components/spinner/test/inverted/index.html
  packages/core/src/components/spinner/test/inverted/spinner.e2e.ts
  packages/core/src/components/spinner/test/inverted/spinner.e2e.ts-snapshots/tds-spinner-inverted-renders-inverted-spinner-correctly-1-linux.png
  packages/core/src/components/spinner/test/standard/index.html
  packages/core/src/components/spinner/test/standard/spinner.e2e.ts
  packages/core/src/components/spinner/test/standard/spinner.e2e.ts-snapshots/tds-spinner-standard-renders-basic-spinner-correctly-1-linux.png
Labels: 🧪 test

#726 feat(popover): close menu programmatically
  packages/core/src/components/popover-canvas/popover-canvas.stories.tsx
  packages/core/src/components/popover-canvas/popover-canvas.tsx
  packages/core/src/components/popover-canvas/readme.md
  packages/core/src/components/popover-canvas/test/default/index.html
  packages/core/src/components/popover-canvas/test/default/popover-canvas.e2e.ts
  packages/core/src/components/popover-canvas/test/default/popover-canvas.e2e.ts-snapshots/tds-popover-canvas-default-renders-default-popover-canvas-correctly-1-linux.png
  packages/core/src/components/popover-core/popover-core.tsx
  packages/core/src/components/popover-core/readme.md
  packages/core/src/components/popover-menu/popover-menu.stories.tsx
  packages/core/src/components/popover-menu/popover-menu.tsx
  packages/core/src/components/popover-menu/readme.md
  packages/core/src/components/popover-menu/test/default/index.html
  packages/core/src/components/popover-menu/test/default/popover-menu.e2e.ts
Labels: 🆕 feature
