Repository scania-digital-design-system/tegel, pull requests merged in 2024-07, with the labels that each got.

#657 feat(tds-table): added horizontal scroll
  packages/core/src/components/table/table-component-basic.stories.tsx
  packages/core/src/components/table/table-component-horizontal-scroll.stories.tsx
  packages/core/src/components/table/table-footer/table-footer.scss
  packages/core/src/components/table/table-footer/table-footer.tsx
  packages/core/src/components/table/table-header-cell/readme.md
  packages/core/src/components/table/table-header-cell/table-header-cell.tsx
  packages/core/src/components/table/table-toolbar/table-toolbar.scss
  packages/core/src/components/table/table-toolbar/table-toolbar.tsx
  packages/core/src/components/table/table/readme.md
  packages/core/src/components/table/table/table.scss
  packages/core/src/components/table/table/table.tsx
  packages/core/src/mixins/_scrollbar.scss
Labels: 🆕 feature

#669 fix(table): sorting arrow default and direction correction
  packages/core/src/components/icon/readme.md
  packages/core/src/components/table/table-header-cell/readme.md
  packages/core/src/components/table/table-header-cell/table-header-cell.tsx
  packages/core/src/components/table/table/test/sorting/table.e2e.ts-snapshots/tds-table-sorting-column-headers-are-clickable-1-linux.png
Labels: 🍾 improvement

#678 ci(release-scripts): no-verify flag and release-all script update
  .github/workflows/create-release-pr.yml
  .github/workflows/release-all.yml
  .github/workflows/release-angular-17.yml
  .github/workflows/release-angular.yml
  .github/workflows/release-core.yml
  .github/workflows/release-react.yml
Labels: 🍾 improvement

#688 fix(angular-17): dependency on version 17 or higher
  packages/angular-17/projects/components/package-lock.json
  packages/angular-17/projects/components/package.json
Labels: 🏗️ build, 🍾 improvement

#682 build: stencil upgrade, playwright image upgrade, tooltip test improvement
  packages/core/docker-test-runner.js
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/components/tooltip/test/click/tooltip.e2e.ts
  packages/core/src/components/tooltip/test/default/tooltip.e2e.ts
  packages/core/src/components/tooltip/test/default/tooltip.e2e.ts-snapshots/tds-tooltip-renders-the-tooltip-correctly-1-linux.png
  packages/core/src/components/tooltip/test/default/tooltip.e2e.ts-snapshots/tds-tooltip-tooltip-appears-on-button-hover-1-linux.png
Labels: 🏗️ build, 🍾 improvement

#692 ci(playwright): report as comment on pr
  .github/workflows/playwright.yml
  .gitignore
  packages/core/playwright.config.ts
  packages/core/results.json
Labels: 🍾 improvement, 🆕 feature

#697 fix(textarea): scroll in readonly mode
  packages/core/src/components/textarea/textarea.scss
  packages/core/src/components/textarea/textarea.stories.tsx
Labels: 🍾 improvement

#696 fix(dropdown): duplicate value in multiselect
  packages/core/src/components/banner/readme.md
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/icon/readme.md
  packages/core/src/components/table/table-header-cell/readme.md
  packages/core/src/components/toggle/test/disabled/toggle.e2e.ts-snapshots/tds-toggle-Should-have-disabled-attribute-1-linux.png
  packages/core/src/components/tooltip/test/click/tooltip.e2e.ts
  packages/core/src/components/tooltip/test/click/tooltip.e2e.ts-snapshots/tds-tooltip-Should-appears-on-button-click-1-linux.png
  packages/core/src/components/tooltip/test/click/tooltip.e2e.ts-snapshots/tds-tooltip-renders-the-tooltip-correctly-1-linux.png
Labels: 🐛 bug

#700 ci(release-script): merge to main step improvement
  .github/workflows/release-all.yml
  packages/core/results.json
Labels: 🍾 improvement

#702 fix(button): fullbleed 100% rule
  packages/core/src/components/button/button.scss
  packages/core/src/components/popover-canvas/test/default/popover-canvas.e2e.ts
Labels: 🍾 improvement

#689 feat(tegel-styles): migration in monorepo, connection to foundations
  .gitignore
  grid-deprecated/_breakpoints.scss
  grid-deprecated/_grid-deprecated.scss
  grid-deprecated/_mixins.scss
  grid-deprecated/_vars.scss
  grid-deprecated/compile.js
  grid-deprecated/dist/css/grid.css
  grid-deprecated/dist/scss/grid.scss
  grid-deprecated/package-lock.json
  grid-deprecated/package.json
  grid-deprecated/spacing-vars.scss
  grid/_grid.scss
  packages/core/src/components/header/header-hamburger/header-hamburger.scss
  packages/core/src/components/header/header.scss
  packages/core/src/components/side-menu/side-menu-collapse-button/side-menu-collapse-button.scss
  packages/core/src/components/side-menu/side-menu-item/side-menu-item.scss
  packages/core/src/components/side-menu/side-menu.scss
  packages/core/src/global/global.scss
  packages/core/src/global/scania-fonts-selectors.scss
  packages/core/src/global/scania-fonts-vars.scss
  packages/styles/LICENSE
  packages/styles/README.md
  packages/styles/build-css.js
  packages/styles/package-lock.json
  packages/styles/package.json
  packages/styles/scss/ag-grid/ag-grid-styles.scss
  packages/styles/scss/foundations/colors.scss
  packages/styles/scss/foundations/foundation.scss
  packages/styles/scss/foundations/grid.scss
  packages/styles/scss/foundations/logotype.scss
  packages/styles/scss/foundations/spacing.scss
  packages/styles/scss/foundations/typography.scss
  spacing/_spacing-vars.scss
  typography/_scania-fonts-selectors.scss
  typography/_scania-fonts-vars.scss
  typography/_scania-fonts.scss
  typography/scania-fonts.scss
Labels: 🆕 feature

#703 feat(table-expandable-row): added part selector
  packages/core/src/components/table/table-body-row-expandable/readme.md
  packages/core/src/components/table/table-body-row-expandable/table-body-row-expandable.tsx
  packages/core/src/components/table/table/test/expandable-row-part-selector/expandable-row-expanded.e2e.ts
  packages/core/src/components/table/table/test/expandable-row-part-selector/expandable-row-expanded.e2e.ts-snapshots/tds-table-expandable-row-part-selector-part-selector-is-passing-on-correct-background-color-1-linux.png
  packages/core/src/components/table/table/test/expandable-row-part-selector/index.html
Labels: 🆕 feature
