Repository scania-digital-design-system/tegel, pull requests merged in 2024-01, with the labels that each got.

#473 fix(side-menu): collapsed state on mobile view
  packages/core/src/components/side-menu/side-menu.tsx
Labels: 🐛 bug

#474 build(stencil): upgrade to 4.9.0
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/components/dropdown/dropdown-option/readme.md
  packages/core/src/components/dropdown/readme.md
  packages/core/src/components/tabs/folder-tabs/readme.md
  packages/core/src/components/tabs/inline-tabs/readme.md
  packages/core/src/components/tabs/navigation-tabs/readme.md
Labels: 🏗️ build

#475 feat(footer): copyright slot
  packages/core/src/components/footer/footer.tsx
  packages/core/src/components/footer/readme.md
Labels: 🆕 feature

#472 test(side-menu): Adding unit tests
  packages/core/src/components/side-menu/test/collapsible/index.html
  packages/core/src/components/side-menu/test/collapsible/side-menu.e2e.ts
  packages/core/src/components/side-menu/test/collapsible/side-menu.e2e.ts-snapshots/tds-side-menu-collapsible-click-collapse-button-to-close-the-menu-1-linux.png
  packages/core/src/components/side-menu/test/collapsible/side-menu.e2e.ts-snapshots/tds-side-menu-collapsible-renders-collapsible-side-menu-correctly-1-linux.png
  packages/core/src/components/side-menu/test/default/index.html
  packages/core/src/components/side-menu/test/default/side-menu.e2e.ts
  packages/core/src/components/side-menu/test/default/side-menu.e2e.ts-snapshots/tds-side-menu-default-renders-default-side-menu-correctly-1-linux.png
Labels: 🧪 test

#476 fix(dropdown, text-field, textarea): global css bleeding in label and helper text
  packages/core/src/components/footer/test/default/footer.e2e.ts
  packages/core/src/components/footer/test/default/footer.e2e.ts-snapshots/tds-footer-default-renders-default-footer-correctly-1-linux.png
  packages/core/src/global/global.scss
  packages/core/src/global/shame.scss
Labels: 🐛 bug

#460 fix(button): colors update
  color/_tokens.scss
  packages/core/src/components/button/button-vars.scss
Labels: 🐛 bug, 🍾 improvement, QA

#478 fix(dropdown): empty no-result-text prop
  packages/core/src/components/dropdown/dropdown.stories.tsx
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/dropdown/readme.md
  packages/core/src/components/dropdown/test/filter/hide-no-result-message/dropdown.e2e.ts
  packages/core/src/components/dropdown/test/filter/hide-no-result-message/dropdown.e2e.ts-snapshots/tds-dropdown-filter-renders-filter-dropdown-correctly-1-linux.png
  packages/core/src/components/dropdown/test/filter/hide-no-result-message/dropdown.e2e.ts-snapshots/tds-dropdown-filter-typing-non-existing-value-does-not-show-No-results-message-1-linux.png
  packages/core/src/components/dropdown/test/filter/hide-no-result-message/index.html
  packages/core/src/components/footer/footer.tsx
  packages/core/src/components/footer/readme.md
  packages/core/src/components/side-menu/readme.md
  packages/core/src/components/table/table-header-cell/readme.md
Labels: 🐛 bug, 🍾 improvement

#471 test(modal): adding unit tests
  packages/core/src/components/modal/test/default/index.html
  packages/core/src/components/modal/test/default/modal.e2e.ts
  packages/core/src/components/modal/test/default/modal.e2e.ts-snapshots/tds-modal-default-renders-modal-correctly-1-linux.png
  packages/core/src/components/modal/test/open-close/index.html
  packages/core/src/components/modal/test/open-close/modal.e2e.ts
  packages/core/src/components/modal/test/open-close/modal.e2e.ts-snapshots/tds-modal-open-Clicking-Delete-button-closes-the-modal-1-linux.png
  packages/core/src/components/modal/test/open-close/modal.e2e.ts-snapshots/tds-modal-open-Clicking-Open-Modal-button-opens-the-modal-1-linux.png
  packages/core/src/components/modal/test/open-close/modal.e2e.ts-snapshots/tds-modal-open-Modal-is-closed-by-default-1-linux.png
  packages/core/src/components/modal/test/prevent-true/index.html
  packages/core/src/components/modal/test/prevent-true/modal.e2e.ts
Labels: 🧪 test

#485 feat(table-header-cell): added slot
  packages/core/src/components/table/table-header-cell/readme.md
  packages/core/src/components/table/table-header-cell/table-header-cell.tsx
Labels: 🆕 feature

#490 fix(modal): medium screen and xs size
  packages/core/src/components/modal/modal.scss
Labels: 🍾 improvement

#487 fix(dropdown-filter): disabled can be opened
  packages/core/src/components/accordion/test/expanded/accordion.e2e.ts-snapshots/tds-accordion-renders-expanded-accordion-correctly-1-linux.png
  packages/core/src/components/dropdown/dropdown-filter.scss
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/dropdown/test/default/disabled/dropdown.e2e.ts
  packages/core/src/components/dropdown/test/default/disabled/dropdown.e2e.ts-snapshots/tds-dropdown-disabled-clicking-the-dropdown-icon-does-not-open-the-dropdown-list-1-linux.png
  packages/core/src/components/dropdown/test/default/disabled/dropdown.e2e.ts-snapshots/tds-dropdown-disabled-clicking-the-dropdown-icon-does-not-opens-the-dropdown-list-1-linux.png
  packages/core/src/components/dropdown/test/default/disabled/index.html
  packages/core/src/components/dropdown/test/filter/disabled/dropdown.e2e.ts
  packages/core/src/components/dropdown/test/filter/disabled/dropdown.e2e.ts-snapshots/tds-dropdown-filter-disabled-clicking-the-dropdown-icon-does-not-open-the-dropdown-list-1-linux.png
  packages/core/src/components/dropdown/test/filter/disabled/index.html
  packages/core/src/components/dropdown/test/multiselect/disabled/dropdown.e2e.ts
  packages/core/src/components/dropdown/test/multiselect/disabled/dropdown.e2e.ts-snapshots/tds-dropdown-multiselect-disabled-clicking-the-dropdown-icon-does-not-open-the-dropdown-list-1-linux.png
  packages/core/src/components/dropdown/test/multiselect/disabled/dropdown.e2e.ts-snapshots/tds-dropdown-multiselect-disabled-clicking-the-dropdown-icon-does-not-opens-the-dropdown-list-1-linux.png
  packages/core/src/components/dropdown/test/multiselect/disabled/index.html
  packages/core/src/components/link/test/disabled/link.e2e.ts-snapshots/tds-link-disabled-disabled-link-is-rendered-correctly-1-linux.png
Labels: 🐛 bug, 🧪 test

#493 build: test files and stories removed from shipping
  packages/core/tsconfig.json
Labels: 🏗️ build

#495 release: tegel@1.5.0
  packages/angular/package-lock.json
  packages/angular/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/react/package-lock.json
  packages/react/package.json
Labels: 🎉 release
