Repository scania-digital-design-system/tegel, pull requests merged in 2024-02, with the labels that each got.

#497 build(stencil): 4.12.0
  packages/core/package-lock.json
  packages/core/package.json
Labels: 🏗️ build

#496 feat(text-field): adding number type and min-max attributes
  packages/core/src/components/text-field/readme.md
  packages/core/src/components/text-field/text-field.stories.tsx
  packages/core/src/components/text-field/text-field.tsx
Labels: 🍾 improvement, 🆕 feature

#500 feat(datetime): setValue method
  packages/core/src/components/datetime/datetime.tsx
  packages/core/src/components/datetime/readme.md
Labels: 🆕 feature

#499 feat(table): disabled state of checkbox in multiselect rows
  packages/core/src/components/table/table-body-row/readme.md
  packages/core/src/components/table/table-body-row/table-body-row.tsx
  packages/core/src/components/table/table-component-multiselect.stories.tsx
  packages/core/src/components/table/table-header/readme.md
  packages/core/src/components/table/table-header/table-header.tsx
  packages/core/src/components/table/table/test/multiselect/default/index.html
  packages/core/src/components/table/table/test/multiselect/default/table.e2e.ts
  packages/core/src/components/table/table/test/multiselect/default/table.e2e.ts-snapshots/tds-table-multiselect-can-check-every-checkbox-in-the-table-1-linux.png
  packages/core/src/components/table/table/test/multiselect/default/table.e2e.ts-snapshots/tds-table-multiselect-renders-multiselect-table-correctly-1-linux.png
  packages/core/src/components/table/table/test/multiselect/disabled-rows/index.html
  packages/core/src/components/table/table/test/multiselect/disabled-rows/table.e2e.ts
  packages/core/src/components/table/table/test/multiselect/disabled-rows/table.e2e.ts-snapshots/tds-table-multiselect-disabled-can-check-enabled-checkbox-in-the-table-1-linux.png
  packages/core/src/components/table/table/test/multiselect/disabled-rows/table.e2e.ts-snapshots/tds-table-multiselect-disabled-renders-multiselect-table-correctly-1-linux.png
Labels: 🆕 feature

#503 fix: release sync
  packages/angular/package-lock.json
  packages/angular/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/components/datetime/readme.md
  packages/react/package-lock.json
  packages/react/package.json
Labels: 🎉 release

#504 fix(icon): a11y
  packages/core/src/components/icon/icon.stories.tsx
  packages/core/src/components/icon/icon.tsx
Labels: 🍾 improvement

#505 ci(release-scripts): run on develop and release all
  .github/workflows/create-release-pr.yml
  .github/workflows/release-all.yml
  .github/workflows/release-angular.yml
  .github/workflows/release-core.yml
  .github/workflows/release-react.yml
Labels: 🎉 release, 🍾 improvement

#507 test(radio-button): added unit test
  packages/core/src/components/radio-button/test/default/index.html
  packages/core/src/components/radio-button/test/default/radio-button.e2e.ts
  packages/core/src/components/radio-button/test/default/radio-button.e2e.ts-snapshots/TdsRadioButton-component-tests-Radio-buttons-w-dd5e3-text-1-and-Label-text-2-render-on-the-page-1-linux.png
  packages/core/src/components/radio-button/test/disabled/index.html
  packages/core/src/components/radio-button/test/disabled/radio-button.e2e.ts
  packages/core/src/components/radio-button/test/disabled/radio-button.e2e.ts-snapshots/Radio-button---disabled-state-Radio-buttons-wi-f7a5d-text-1-and-Label-text-2-render-on-the-page-1-linux.png
Labels: 🧪 test

#516 feat(tooltip): Adds offsetSkidding and offsetDistance props for the tooltip
  packages/core/src/components/tooltip/tooltip.stories.tsx
Labels: 🆕 feature

#514 fix(datetime): corrected custom event
  packages/core/src/components/datetime/datetime.stories.tsx
  packages/core/src/components/datetime/datetime.tsx
  packages/core/src/components/datetime/readme.md
  packages/core/src/components/icon/readme.md
  packages/core/src/components/radio-button/test/disabled/radio-button.e2e.ts-snapshots/Radio-button---disabled-state-Radio-buttons-wi-52667-ext-1-and-Label-text-2-renders-on-the-page-1-linux.png
Labels: 🍾 improvement

#515 docs: remove netlify links in readmes and stories
  .github/CODE_STYLE.md
  README.md
  packages/angular/README.md
  packages/core/README.md
  packages/core/src/stories/announcements/announce-tegel.stories.ts
  packages/react/README.md
Labels: 📜 docs
