Repository scania-digital-design-system/tegel, pull requests merged in 2024-10, with the labels that each got.

#774 feat(table): zebra rows & columns
  packages/core/src/components/banner/readme.md
  packages/core/src/components/icon/readme.md
  packages/core/src/components/table/table-body-cell/table-body-cell.tsx
  packages/core/src/components/table/table-body/table-body.scss
  packages/core/src/components/table/table-body/table-body.tsx
  packages/core/src/components/table/table-component-zebra.stories.tsx
  packages/core/src/components/table/table-header-cell/readme.md
  packages/core/src/components/table/table-vars.scss
  packages/core/src/components/table/table/readme.md
  packages/core/src/components/table/table/table.tsx
  packages/core/src/components/table/table/test/zebra-mode/columns-even/index.html
  packages/core/src/components/table/table/test/zebra-mode/columns-even/table.e2e.ts
  packages/core/src/components/table/table/test/zebra-mode/columns-even/table.e2e.ts-snapshots/tds-table-zebra-mode-columns-even-renders-default-table-correctly-1-linux.png
  packages/core/src/components/table/table/test/zebra-mode/columns-odd/index.html
  packages/core/src/components/table/table/test/zebra-mode/columns-odd/table.e2e.ts
  packages/core/src/components/table/table/test/zebra-mode/columns-odd/table.e2e.ts-snapshots/tds-table-zebra-mode-columns-odd-renders-default-table-correctly-1-linux.png
  packages/core/src/components/table/table/test/zebra-mode/rows-even/index.html
  packages/core/src/components/table/table/test/zebra-mode/rows-even/table.e2e.ts
  packages/core/src/components/table/table/test/zebra-mode/rows-even/table.e2e.ts-snapshots/tds-table-zebra-mode-rows-even-renders-default-table-correctly-1-linux.png
  packages/core/src/components/table/table/test/zebra-mode/rows-odd/index.html
  packages/core/src/components/table/table/test/zebra-mode/rows-odd/table.e2e.ts
  packages/core/src/components/table/table/test/zebra-mode/rows-odd/table.e2e.ts-snapshots/tds-table-zebra-mode-rows-odd-renders-default-table-correctly-1-linux.png
Labels: 👩‍🎨 design

#798 fix(utility-stories): convert to TS and bring 'em back
  packages/core/src/stories/utility/utility-classes/align.stories.mdx
  packages/core/src/stories/utility/utility-classes/align.stories.ts
  packages/core/src/stories/utility/utility-classes/display.stories.mdx
  packages/core/src/stories/utility/utility-classes/display.stories.ts
  packages/core/src/stories/utility/utility-classes/flex.stories.mdx
  packages/core/src/stories/utility/utility-classes/flex.stories.ts
  packages/core/src/stories/utility/utility-classes/float.stories.mdx
  packages/core/src/stories/utility/utility-classes/float.stories.ts
  packages/core/src/stories/utility/utility-classes/gap.stories.mdx
  packages/core/src/stories/utility/utility-classes/gap.stories.ts
  packages/core/src/stories/utility/utility-classes/height.stories.mdx
  packages/core/src/stories/utility/utility-classes/height.stories.ts
  packages/core/src/stories/utility/utility-classes/justify.stories.mdx
  packages/core/src/stories/utility/utility-classes/justify.stories.ts
  packages/core/src/stories/utility/utility-classes/margin.stories.mdx
  packages/core/src/stories/utility/utility-classes/margin.stories.ts
  packages/core/src/stories/utility/utility-classes/opacity.stories.mdx
  packages/core/src/stories/utility/utility-classes/opacity.stories.ts
  packages/core/src/stories/utility/utility-classes/overflow.stories.mdx
  packages/core/src/stories/utility/utility-classes/overflow.stories.ts
  packages/core/src/stories/utility/utility-classes/padding.stories.mdx
  packages/core/src/stories/utility/utility-classes/padding.stories.ts
  packages/core/src/stories/utility/utility-classes/placement.stories.mdx
  packages/core/src/stories/utility/utility-classes/placement.stories.ts
  packages/core/src/stories/utility/utility-classes/position.stories.mdx
  packages/core/src/stories/utility/utility-classes/position.stories.ts
  packages/core/src/stories/utility/utility-classes/text-alignment.stories.mdx
  packages/core/src/stories/utility/utility-classes/text-alignment.stories.ts
  packages/core/src/stories/utility/utility-classes/visibility.stories.mdx
  packages/core/src/stories/utility/utility-classes/visibility.stories.ts
  packages/core/src/stories/utility/utility-classes/width.stories.mdx
  packages/core/src/stories/utility/utility-classes/width.stories.ts
  packages/core/src/stories/utility/utility-classes/z-index.stories.mdx
  packages/core/src/stories/utility/utility-classes/z-index.stories.ts
Labels: 🐛 bug

#796 fix(breadbrumbs): update CSS selector to .current since .current is always last.
  packages/core/src/components/breadcrumbs/breadcrumb/breadcrumb.scss
Labels: :handshake: contribution

#789 feat(table): add part for the cell in the expanded row of the table. add visible for overflow.
  packages/core/src/components/table/table-body-row-expandable/readme.md
  packages/core/src/components/table/table-body-row-expandable/table-body-row-expandable.scss
  packages/core/src/components/table/table-body-row-expandable/table-body-row-expandable.tsx
  packages/core/src/components/table/table-component-expandable-rows.stories.tsx
Labels: :handshake: contribution

#811 docs(storybook-table): controls for overflow
  packages/core/src/components/table/table-component-expandable-rows.stories.tsx
Labels: 📜 docs

#808 ci: release script improvements
  .github/workflows/holy-grail.yml
  .github/workflows/release-all.yml
Labels: 🎉 release
