Repository scania-digital-design-system/tegel, pull requests merged in 2024-06, with the labels that each got.

#641 release: tegel 1.9.1
  packages/angular-17/projects/components/package-lock.json
  packages/angular-17/projects/components/package.json
  packages/angular/package-lock.json
  packages/angular/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/react/package-lock.json
  packages/react/package.json
Labels: 🎉 release

#642 Feat/cdep 3325 types for icon names
  icons/gulpfile.js
  packages/core/src/components/banner/banner.tsx
  packages/core/src/components/banner/readme.md
  packages/core/src/components/icon/icon.tsx
  packages/core/src/components/icon/readme.md
  packages/core/src/types/Icons.ts
Labels: 🆕 feature

#644 docs: added angular-17 installation guide
  packages/core/src/stories/Installation/angular-17.stories.ts
Labels: 📜 docs

#659 fix: add missing type definitions
  packages/core/package.json
Labels: 🍾 improvement

#651 feat(footer): add compact footer property
  packages/core/src/components/banner/readme.md
  packages/core/src/components/footer/footer.scss
  packages/core/src/components/footer/footer.stories.tsx
  packages/core/src/components/footer/footer.tsx
  packages/core/src/components/icon/readme.md
Labels: 🆕 feature

#633 docs: creating a component & docs update
  .github/CODE_STYLE.md
  CREATING-COMPONENT.md
  UPDATING-DOCS.MD
Labels: 📜 docs

#663 feat(grid): new grid
  .gitignore
  grid/_grid-deprecated.scss
  packages/core/src/global/global.scss
  packages/core/src/global/grid.scss
  packages/core/src/stories/foundations/grid/grid-deprecated.stories.tsx
  packages/core/src/stories/foundations/grid/grid.stories.tsx
Labels: 🆕 feature
