Repository scania-digital-design-system/tegel, pull requests merged in 2024-09, with the labels that each got.

#732 test(block): added unit test
  packages/core/src/components/block/test/2-level-light-mode/block.e2e.ts
  packages/core/src/components/block/test/2-level-light-mode/block.e2e.ts-snapshots/tds-block-2-level-light-mode-renders-2-level-block-correctly-1-linux.png
  packages/core/src/components/block/test/2-level-light-mode/index.html
  packages/core/src/components/block/test/3-level-dark-mode/block.e2e.ts
  packages/core/src/components/block/test/3-level-dark-mode/block.e2e.ts-snapshots/tds-block-3-level-dark-mode-renders-2-level-block-correctly-1-linux.png
  packages/core/src/components/block/test/3-level-dark-mode/index.html
Labels: 🧪 test

#737 build: release script and wrappers improvement
  .github/workflows/release-all.yml
  .github/workflows/release-angular-17.yml
  .github/workflows/release-angular.yml
  .github/workflows/release-react.yml
  package.json
  packages/angular-17/package-lock.json
  packages/angular-17/package.json
  packages/angular-17/projects/components/ng-package.json
  packages/angular-17/projects/components/package-lock.json
  packages/angular-17/projects/components/package.json
  packages/angular/package-lock.json
  packages/angular/package.json
  packages/angular/projects/components/package-lock.json
  packages/angular/projects/components/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/react/package-lock.json
  packages/react/package.json
  packages/styles/package-lock.json
  packages/styles/package.json
Labels: 🏗️ build

#730 docs(table-libraries): added basic info about tegel, tanstack and ag-grid
  packages/core/src/stories/announcements/table-libraries.stories.ts
Labels: 📜 docs

#736 fix(table): passing on unit value with horizontalscroll
  .github/workflows/release-all.yml
  .github/workflows/release-angular-17.yml
  .github/workflows/release-angular.yml
  .github/workflows/release-react.yml
  package.json
  packages/angular-17/package-lock.json
  packages/angular-17/package.json
  packages/angular-17/projects/components/ng-package.json
  packages/angular-17/projects/components/package-lock.json
  packages/angular/package-lock.json
  packages/angular/projects/components/package-lock.json
  packages/angular/projects/components/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/components/table/table-footer/table-footer.tsx
  packages/core/src/components/table/table-toolbar/table-toolbar.tsx
  packages/core/src/components/table/table/table.tsx
  packages/react/package-lock.json
  packages/styles/package.json
Labels: 🐛 bug
