Repository scania-digital-design-system/tegel, pull requests merged in 2024-03, with the labels that each got.

#513 fix(slider): emit tdsChange on mouse-up and touch-end events
  packages/core/src/components/datetime/readme.md
  packages/core/src/components/icon/readme.md
  packages/core/src/components/popover-core/readme.md
  packages/core/src/components/slider/readme.md
  packages/core/src/components/slider/slider.stories.tsx
  packages/core/src/components/slider/slider.tsx
  packages/core/src/components/text-field/readme.md
Labels: 🍾 improvement

#550 feat(toast): make close button optional
  packages/core/src/components/toast/readme.md
  packages/core/src/components/toast/toast.scss
  packages/core/src/components/toast/toast.stories.tsx
  packages/core/src/components/toast/toast.tsx
Labels: 🆕 feature

#544 ci: release all script improvement
  .github/workflows/release-all.yml
Labels: 🍾 improvement

#552 feat(modal): re-initilize selector and clean-up method
  packages/core/src/components/modal/modal.stories.tsx
  packages/core/src/components/modal/modal.tsx
  packages/core/src/components/modal/readme.md
Labels: 🍾 improvement, 🆕 feature

#553 build(stencil): v4.12.6
  packages/core/package-lock.json
  packages/core/package.json
Labels: 🏗️ build

#554 fix(text-field): read-only hides suffix icon
  packages/core/src/components/text-field/readme.md
  packages/core/src/components/text-field/test/read-only-with-suffix/index.html
  packages/core/src/components/text-field/test/read-only-with-suffix/text-field.e2e.ts
  packages/core/src/components/text-field/text-field.scss
  packages/core/src/components/text-field/text-field.tsx
Labels: 🍾 improvement, 🪆 refactor

#558 test(text-field): default test case
  packages/core/src/components/table/table/test/expandable-row/table.e2e.ts
  packages/core/src/components/table/table/test/filtering/table.e2e.ts
  packages/core/src/components/text-field/test/default/index.html
  packages/core/src/components/text-field/test/default/text-field.e2e.ts
  packages/core/src/components/text-field/test/default/text-field.e2e.ts-snapshots/TdsTextField---default-state-renders-default-text-field-correctly-1-linux.png
Labels: 🧪 test

#559 test(table): add text-align attribute to table body cells
  packages/core/src/components/table/table/test/batch/index.html
  packages/core/src/components/table/table/test/default/index.html
  packages/core/src/components/table/table/test/expandable-row/index.html
  packages/core/src/components/table/table/test/filtering/index.html
  packages/core/src/components/table/table/test/filtering/table.e2e.ts-snapshots/tds-table-filtering-clicking-on-search-button-opens-field-for-entering-data-1-linux.png
  packages/core/src/components/table/table/test/filtering/table.e2e.ts-snapshots/tds-table-filtering-look-for-textbox-and-click-it-1-linux.png
  packages/core/src/components/table/table/test/filtering/table.e2e.ts-snapshots/tds-table-filtering-renders-filtering-table-correctly-1-linux.png
  packages/core/src/components/table/table/test/multiselect/default/index.html
  packages/core/src/components/table/table/test/multiselect/disabled-rows/index.html
  packages/core/src/components/table/table/test/pagination/index.html
  packages/core/src/components/table/table/test/sorting/index.html
  packages/core/src/components/table/table/test/sorting/table.e2e.ts-snapshots/tds-table-sorting-column-headers-are-clickable-1-linux.png
  packages/core/src/components/table/table/test/sorting/table.e2e.ts-snapshots/tds-table-sorting-renders-sorting-table-correctly-1-linux.png
Labels: 🧪 test

#564 fix(table-body-cell): map text-align prop in lifecycle
  packages/core/src/components/table/table-body-cell/readme.md
  packages/core/src/components/table/table-body-cell/table-body-cell.tsx
  packages/core/src/components/table/table/test/filtering/table.e2e.ts
  packages/core/src/components/table/table/test/sorting/table.e2e.ts
Labels: 🍾 improvement
