Repository scania-digital-design-system/tegel, pull requests merged in 2024-05, with the labels that each got.

#611 docs(contribution): link correction
  README.md
Labels: 📜 docs

#545 fix(tds-dropdown): improved scrollbar styling
  packages/core/src/components/dropdown/dropdown-button.scss
  packages/core/src/components/dropdown/dropdown-vars.scss
  packages/core/src/components/dropdown/dropdown.scss
  packages/core/src/components/dropdown/dropdown.stories.tsx
  packages/core/src/components/modal/modal.stories.tsx
  packages/core/src/global/global.scss
  packages/core/src/global/scrollbar-vars.scss
  packages/core/src/mixins/_scrollbar.scss
  packages/core/src/stories/patterns/navigation/navigation-manyitems.stories.tsx
Labels: 🍾 improvement

#618 feat(side-menu): :sparkles: programatically toggle side menu dropdown
  packages/core/src/components/side-menu/side-menu-dropdown/readme.md
  packages/core/src/components/side-menu/side-menu-dropdown/side-menu-dropdown.tsx
  packages/core/src/components/side-menu/side-menu.stories.tsx
  packages/core/src/components/side-menu/test/expand-toggle/expand-toggle.e2e.ts
  packages/core/src/components/side-menu/test/expand-toggle/expand-toggle.e2e.ts-snapshots/tds-side-menu-toggle-expand-collapse-programmatically-and-expand-on-the-UI-1-linux.png
  packages/core/src/components/side-menu/test/expand-toggle/expand-toggle.e2e.ts-snapshots/tds-side-menu-toggle-expand-toggle-collapse-and-expand-programmatically-1-linux.png
  packages/core/src/components/side-menu/test/expand-toggle/index.html
  packages/core/src/components/tabs/test/folder-tabs/folder-tabs.e2e.ts
  packages/core/src/components/tabs/test/inline-tabs/inline-tabs.e2e.ts
  packages/core/src/components/tabs/test/navigation-tabs/navigation-tabs.e2e.ts
Labels: 🆕 feature

#621 fix(side-menu) remove extra space to the right of a collapsed side menu item in desktop
  packages/core/src/components/side-menu/side-menu-dropdown/side-menu-dropdown.scss
  packages/core/src/components/side-menu/side-menu.scss
Labels: :handshake: contribution

#624 ci(test): unit test to run on push commit instead of commit
  .husky/pre-commit
  .husky/pre-push
Labels: 🧪 test

#612 feat(table): default expanded row, expand/collapse methods, tdsChange event
  packages/core/src/components/dropdown/test/filter/dropdown.e2e.ts-snapshots/tds-dropdown-filter-reset-button-icon-appears-when-typing-in-the-filter-input-1-linux.png
  packages/core/src/components/table/table-body-row-expandable/readme.md
  packages/core/src/components/table/table-body-row-expandable/table-body-row-expandable.tsx
  packages/core/src/components/table/table-component-expandable-rows.stories.tsx
  packages/core/src/components/table/table/test/expandable-row-expanded/expandable-row-expanded.e2e.ts
  packages/core/src/components/table/table/test/expandable-row-expanded/expandable-row-expanded.e2e.ts-snapshots/tds-table-expandable-row-expanded-click-on-expand-input---should-become-unchecked-for-row-id-1-1-linux.png
  packages/core/src/components/table/table/test/expandable-row-expanded/expandable-row-expanded.e2e.ts-snapshots/tds-table-expandable-row-expanded-first-row-is-expanded-1-linux.png
  packages/core/src/components/table/table/test/expandable-row-expanded/index.html
  packages/core/src/components/table/table/test/expandable-row-methods/expandable-row-methods.e2e.ts
  packages/core/src/components/table/table/test/expandable-row-methods/expandable-row-methods.e2e.ts-snapshots/tds-table-expandable-row-methods-click-collapse-button-1-linux.png
  packages/core/src/components/table/table/test/expandable-row-methods/expandable-row-methods.e2e.ts-snapshots/tds-table-expandable-row-methods-click-expand-button-1-linux.png
  packages/core/src/components/table/table/test/expandable-row-methods/index.html
Labels: 🆕 feature

#626 feat (accordion): add prop for removing the last accordion item bottom border
  packages/core/src/components/accordion/accordion.scss
  packages/core/src/components/accordion/accordion.stories.tsx
  packages/core/src/components/accordion/accordion.tsx
  packages/core/src/components/accordion/readme.md
  packages/core/src/components/accordion/test/hide-last-border/accordion.e2e.ts
  packages/core/src/components/accordion/test/hide-last-border/accordion.e2e.ts-snapshots/tds-accordion-renders-accordion-with-hidden-last-border-correctly-1-linux.png
  packages/core/src/components/accordion/test/hide-last-border/index.html
  packages/core/src/components/table/table-header-cell/readme.md
Labels: 🆕 feature, :handshake: contribution
