Repository scania-digital-design-system/tegel, pull requests merged in 2024-11, with the labels that each got.

#825 feat: icon gallery
  packages/core/src/components/icon/icon.stories.tsx
  packages/core/src/stories/foundations/icons-gallery.stories.tsx
Labels: 📜 docs, 🆕 feature

#837 fix: align input text colors
  packages/core/src/components/dropdown/dropdown-filter.scss
  packages/core/src/components/dropdown/dropdown-option/dropdown-option-vars.scss
  packages/core/src/components/dropdown/dropdown-vars.scss
  packages/core/src/components/dropdown/test/basic/dropdown.e2e.ts-snapshots/tds-dropdown-basic-clicking-the-dropdown-button-opens-the-dropdown-list-1-linux.png
  packages/core/src/components/dropdown/test/basic/dropdown.e2e.ts-snapshots/tds-dropdown-basic-renders-basic-dropdown-correctly-1-linux.png
  packages/core/src/components/dropdown/test/default/disabled/dropdown.e2e.ts-snapshots/tds-dropdown-disabled-clicking-the-dropdown-icon-does-not-open-the-dropdown-list-1-linux.png
  packages/core/src/components/dropdown/test/default/dropdown.e2e.ts-snapshots/tds-dropdown-default-clicking-the-dropdown-button-opens-the-dropdown-list-1-linux.png
  packages/core/src/components/dropdown/test/default/dropdown.e2e.ts-snapshots/tds-dropdown-default-clicking-the-dropdown-opens-the-dropdown-list-then-click-Option-1-1-linux.png
  packages/core/src/components/dropdown/test/default/dropdown.e2e.ts-snapshots/tds-dropdown-default-renders-default-dropdown-correctly-1-linux.png
  packages/core/src/components/dropdown/test/error/dropdown.e2e.ts-snapshots/tds-dropdown-error-clicking-the-dropdown-opens-the-dropdown-list-1-linux.png
  packages/core/src/components/dropdown/test/error/dropdown.e2e.ts-snapshots/tds-dropdown-error-renders-error-dropdown-correctly-1-linux.png
  packages/core/src/components/dropdown/test/filter/dropdown.e2e.ts-snapshots/tds-dropdown-filter-Select-option-from-dropdown-list-and-check-if-the-input-value-is-updated-1-linux.png
  packages/core/src/components/dropdown/test/filter/dropdown.e2e.ts-snapshots/tds-dropdown-filter-renders-filter-dropdown-correctly-1-linux.png
  packages/core/src/components/dropdown/test/filter/dropdown.e2e.ts-snapshots/tds-dropdown-filter-toggle-dropdown-visibility-and-select-option-two-1-linux.png
  packages/core/src/components/dropdown/test/filter/hide-no-result-message/dropdown.e2e.ts-snapshots/tds-dropdown-filter-renders-filter-dropdown-correctly-1-linux.png
  packages/core/src/components/dropdown/test/filter/hide-no-result-message/dropdown.e2e.ts-snapshots/tds-dropdown-filter-typing-non-existing-value-does-not-show-No-results-message-1-linux.png
  packages/core/src/components/dropdown/test/filter/normalize-text-false/dropdown.e2e.ts-snapshots/tds-dropdown-filter-renders-filter-dropdown-correctly-1-linux.png
  packages/core/src/components/dropdown/test/multiselect/dropdown.e2e.ts-snapshots/tds-dropdown-multiselect-clicking-the-dropdown-a2125--dropdown-list-then-click-on-all-the-options-1-linux.png
  packages/core/src/components/dropdown/test/multiselect/dropdown.e2e.ts-snapshots/tds-dropdown-multiselect-clicking-the-dropdown-de184-ist-then-click-Option-1-should-not-close-it-1-linux.png
  packages/core/src/components/dropdown/test/multiselect/dropdown.e2e.ts-snapshots/tds-dropdown-multiselect-renders-multiselect-dropdown-correctly-1-linux.png
  packages/core/src/components/text-field/test/password-error/text-field.e2e.ts-snapshots/TdsTextField---password-type-with-error-state-renders-default-text-field-correctly-1-linux.png
  packages/core/src/components/text-field/test/password-error/text-field.e2e.ts-snapshots/TdsTextField---password-type-with-error-state-should-handle-hover-click-and-input-on-text-field-1-linux.png
  packages/core/src/components/text-field/text-field-vars.scss
  packages/core/src/components/text-field/text-field.scss
  packages/core/src/components/textarea/textarea-vars.scss
  packages/core/src/components/textarea/textarea.scss
  packages/core/src/components/toggle/toggle-vars.scss
Labels: 🐛 bug

#847 fix(text-field): label inside
  packages/core/src/components/text-field/text-field.tsx
Labels: 🍾 improvement

#839 feat(popover-core): prevent internal logic
  packages/core/src/components/popover-canvas/popover-canvas.tsx
  packages/core/src/components/popover-canvas/readme.md
  packages/core/src/components/popover-core/popover-core.tsx
  packages/core/src/components/popover-core/readme.md
  packages/core/src/components/popover-menu/popover-menu.tsx
  packages/core/src/components/popover-menu/readme.md
  packages/core/src/components/table/table-header-cell/readme.md
  packages/core/src/components/tooltip/readme.md
  packages/core/src/components/tooltip/tooltip.tsx
Labels: 🍾 improvement, 🆕 feature

#855 fix(button): host in disabled state
  packages/core/src/components/button/button.scss
  packages/core/src/components/button/button.tsx
Labels: 🐛 bug, 🍾 improvement
