Repository scania-digital-design-system/tegel, pull requests merged in 2025-10, with the labels that each got.

#1443 fix: updating chip colors for better contrast
  packages/core/src/components/chip/chip-vars.scss
  packages/core/src/components/chip/chip.scss
  packages/core/src/components/chip/test/checkbox/chip.e2e.ts
  packages/core/src/components/chip/test/checkbox/chip.e2e.ts-snapshots/tds-chip-checkbox-darkmode-renders-checkbox-chips-correctly-1-linux.png
  packages/core/src/components/chip/test/checkbox/chip.e2e.ts-snapshots/tds-chip-checkbox-lightmode-renders-checkbox-chips-correctly-1-linux.png
  packages/core/src/components/chip/test/default/chip.e2e.ts
  packages/core/src/components/chip/test/default/chip.e2e.ts-snapshots/tds-chip-default-darkmode-renders-default-chip-correctly-1-linux.png
  packages/core/src/components/chip/test/default/chip.e2e.ts-snapshots/tds-chip-default-lightmode-renders-default-chip-correctly-1-linux.png
  packages/core/src/components/chip/test/disabled/chip.e2e.ts-snapshots/tds-chip-button-darkmode-renders-button-chips-correctly-1-linux.png
  packages/core/src/components/chip/test/disabled/chip.e2e.ts-snapshots/tds-chip-button-lightmode-renders-button-chips-correctly-1-linux.png
  packages/core/src/components/chip/test/disabled/chip.e2e.ts-snapshots/tds-chip-checkbox-darkmode-renders-checkbox-chips-correctly-1-linux.png
  packages/core/src/components/chip/test/disabled/chip.e2e.ts-snapshots/tds-chip-checkbox-lightmode-renders-checkbox-chips-correctly-1-linux.png
  packages/core/src/components/chip/test/disabled/chip.e2e.ts-snapshots/tds-chip-radio-darkmode-renders-radio-chips-correctly-1-linux.png
  packages/core/src/components/chip/test/disabled/chip.e2e.ts-snapshots/tds-chip-radio-lightmode-renders-radio-chips-correctly-1-linux.png
  packages/core/src/components/chip/test/icon/chip.e2e.ts-snapshots/tds-chip-default-darkmode-renders-default-chip-correctly-1-linux.png
  packages/core/src/components/chip/test/icon/chip.e2e.ts-snapshots/tds-chip-default-lightmode-renders-default-chip-correctly-1-linux.png
  packages/core/src/components/chip/test/radio/chip.e2e.ts
  packages/core/src/components/chip/test/radio/chip.e2e.ts-snapshots/tds-chip-radio-darkmode-renders-radio-chips-correctly-1-linux.png
  packages/core/src/components/chip/test/radio/chip.e2e.ts-snapshots/tds-chip-radio-lightmode-renders-radio-chips-correctly-1-linux.png
  packages/core/src/tests/form-test/form-test.e2e.ts-snapshots/form-test-fill-form-and-reset-1-linux.png
  packages/core/src/tests/form-test/form-test.e2e.ts-snapshots/form-test-fill-form-and-reset-2-linux.png
Labels: ✅ design approved

#1471 feat: update typography
  packages/core/src/components/banner/banner.scss
  packages/core/src/components/block/block.scss
  packages/core/src/components/button/button.scss
  packages/core/src/components/footer/footer.scss
  packages/core/src/components/slider/slider.scss
  packages/core/src/components/text-field/text-field.scss
  packages/core/src/components/toggle/toggle.scss
  typography/_scania-fonts-selectors.scss
  typography/mixins/_type-styles.scss
  typography/tokens/_typography-scania.scss
  typography/tokens/_typography-traton.scss
  typography/utilities/_typography-utility.scss
Labels: 👩‍🎨 design

#1483 Fix(message): color update
  packages/core/src/components/message/message-vars.scss
  packages/core/src/components/message/message.scss
  packages/core/src/components/message/test/basic/message.e2e.ts
  packages/core/src/components/message/test/basic/message.e2e.ts-snapshots/tds-message-basic-primary-darkmode-is-basic-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/basic/message.e2e.ts-snapshots/tds-message-basic-primary-lightmode-is-basic-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/basic/message.e2e.ts-snapshots/tds-message-basic-secondary-darkmode-is-basic-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/basic/message.e2e.ts-snapshots/tds-message-basic-secondary-lightmode-is-basic-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/error/message.e2e.ts
  packages/core/src/components/message/test/error/message.e2e.ts-snapshots/tds-message-error-primary-darkmode-is-error-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/error/message.e2e.ts-snapshots/tds-message-error-primary-lightmode-is-error-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/error/message.e2e.ts-snapshots/tds-message-error-secondary-darkmode-is-error-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/error/message.e2e.ts-snapshots/tds-message-error-secondary-lightmode-is-error-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/information/message.e2e.ts
  packages/core/src/components/message/test/information/message.e2e.ts-snapshots/tds-message-information-primary-darkmode-is-information-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/information/message.e2e.ts-snapshots/tds-message-information-primary-lightmode-is-information-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/information/message.e2e.ts-snapshots/tds-message-information-secondary-darkmode-is-information-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/information/message.e2e.ts-snapshots/tds-message-information-secondary-lightmode-is-information-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/success/message.e2e.ts
  packages/core/src/components/message/test/success/message.e2e.ts-snapshots/tds-message-success-primary-darkmode-is-success-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/success/message.e2e.ts-snapshots/tds-message-success-primary-lightmode-is-success-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/success/message.e2e.ts-snapshots/tds-message-success-secondary-darkmode-is-success-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/success/message.e2e.ts-snapshots/tds-message-success-secondary-lightmode-is-success-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/warning/message.e2e.ts
  packages/core/src/components/message/test/warning/message.e2e.ts-snapshots/tds-message-warning-primary-darkmode-is-warning-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/warning/message.e2e.ts-snapshots/tds-message-warning-primary-lightmode-is-warning-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/warning/message.e2e.ts-snapshots/tds-message-warning-secondary-darkmode-is-warning-message-rendered-correctly-1-linux.png
  packages/core/src/components/message/test/warning/message.e2e.ts-snapshots/tds-message-warning-secondary-lightmode-is-warning-message-rendered-correctly-1-linux.png
Labels: 👩‍🎨 design, ✅ design approved
